#!/bin/bash
# fetch_versions.sh — Build multi-version test matrix from rubygems.org
#
# For each gem in gem_manifest.tsv, queries the rubygems.org versions API
# and writes the latest N stable (non-prerelease, non-yanked) versions
# to version_matrix.tsv.
#
# Usage:
#   ./tests/wowx/fetch_versions.sh              # latest 3 versions per gem
#   ./tests/wowx/fetch_versions.sh --count 5    # latest 5 versions per gem
#   ./tests/wowx/fetch_versions.sh --count 1    # latest only
#
# Requires: curl, jq

set -uo pipefail

# ── Paths ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$SCRIPT_DIR/gem_manifest.tsv"
OUTPUT="$SCRIPT_DIR/version_matrix.tsv"
COUNT=3

# ── Options ───────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --count) COUNT="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^$/{ s/^# //; s/^#$//; p }' "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# ── Colours ───────────────────────────────────────────────────────────

if [ -t 2 ]; then
    GREEN='\033[32m'  RED='\033[31m'  DIM='\033[2m'
    BOLD='\033[1m'    RESET='\033[0m'
else
    GREEN='' RED='' DIM='' BOLD='' RESET=''
fi

log()  { printf "%b\n" "$*" >&2; }
info() { log "${DIM}$*${RESET}"; }

# ── Collect gem names from manifest ───────────────────────────────────

declare -a GEMS=()

while IFS=$'\t' read -r gem _exe _flag _tags; do
    [[ "$gem" =~ ^#.*$ ]] && continue
    [[ -z "$gem" ]] && continue
    GEMS+=("$gem")
done < "$MANIFEST"

if [ ${#GEMS[@]} -eq 0 ]; then
    log "${RED}error:${RESET} no gems found in $MANIFEST"
    exit 1
fi

log "${BOLD}Fetching versions for ${#GEMS[@]} gems (latest $COUNT each)${RESET}"

# ── Fetch versions in parallel ────────────────────────────────────────

tmpdir=$(mktemp -d)

for gem in "${GEMS[@]}"; do
    (
        curl -sf "https://rubygems.org/api/v1/versions/${gem}.json" \
            -o "$tmpdir/$gem.json"
    ) &
done
wait

# ── Parse and write matrix ────────────────────────────────────────────

{
    echo "# version_matrix.tsv — generated by fetch_versions.sh"
    echo "# $(date -Iseconds)"
    echo "# Latest $COUNT stable versions per gem"
    echo "#"
    echo "# gem_name	version"
} > "$OUTPUT"

fetched=0
failed=0

for gem in "${GEMS[@]}"; do
    json="$tmpdir/$gem.json"
    if [ ! -f "$json" ] || [ ! -s "$json" ]; then
        log "${RED}  FAIL${RESET} $gem (no response)"
        failed=$((failed + 1))
        continue
    fi

    # Filter: not prerelease, not yanked, take latest N
    # The versions API returns an array sorted newest-first
    versions=$(jq -r "
        [.[] | select(.prerelease == false and (.yanked // false) == false)]
        | .[0:$COUNT]
        | .[].number
    " "$json" 2>/dev/null)

    if [ -z "$versions" ]; then
        log "${RED}  FAIL${RESET} $gem (no stable versions found)"
        failed=$((failed + 1))
        continue
    fi

    ver_count=0
    while IFS= read -r ver; do
        [ -z "$ver" ] && continue
        printf '%s\t%s\n' "$gem" "$ver" >> "$OUTPUT"
        ver_count=$((ver_count + 1))
    done <<< "$versions"

    info "  $gem: $ver_count versions"
    fetched=$((fetched + 1))
done

rm -rf "$tmpdir"

# ── Summary ───────────────────────────────────────────────────────────

log ""
log "${BOLD}Done:${RESET} ${GREEN}$fetched${RESET} gems fetched"
if [ $failed -gt 0 ]; then
    log "${RED}$failed gem(s) failed${RESET}"
fi
log "Matrix written to: $OUTPUT"
total_versions=$(grep -c -v '^#' "$OUTPUT" 2>/dev/null || echo 0)
log "Total test pairs: $total_versions"
