/* Generated by re2c 3.1 on Tue Feb 17 19:22:07 2026 */
/*
 * lexer.re -- re2c input for Gemfile lexer
 *
 * Tokenises a restricted subset of Gemfile syntax.
 * Token IDs come from the lemon-generated parser.h.
 *
 * Generate: re2c -o src/gemfile/lexer.c src/gemfile/lexer.re --no-debug-info
 */

#include <string.h>
#include "wow/gemfile/lexer.h"
#include "parser.h"

void wow_lexer_init(struct wow_lexer *lex, const char *buf, int len)
{
    lex->cursor = buf;
    lex->limit  = buf + len;
    lex->marker = buf;
    lex->tok    = buf;
    lex->start  = buf;
    lex->line   = 1;
}

/* ------------------------------------------------------------------ */
/* Helpers for multi-line skip patterns                                */
/* ------------------------------------------------------------------ */

/*
 * skip_git_source_block -- consume a git_source(...) { ... } declaration.
 *
 * Called after the lexer has matched "git_source". Advances the cursor
 * past the entire declaration including its block body.
 *
 * Handles:
 *   git_source(:github) { |repo| "https://github.com/#{repo}.git" }
 *   git_source(:github) do |repo|
 *     "https://github.com/#{repo}"
 *   end
 *   git_source :github do |repo| ... end
 */
static int skip_git_source_block(struct wow_lexer *lex, struct wow_token *token)
{
    const char *p = lex->cursor;
    const char *lim = lex->limit;

    /* Phase 1: skip optional (args) or bare :symbol */
    while (p < lim && (*p == ' ' || *p == '\t'))
        p++;
    if (p < lim && *p == '(') {
        p++;
        while (p < lim && *p != ')')
            p++;
        if (p < lim) p++;  /* skip ')' */
    } else if (p < lim && *p == ':') {
        p++;
        while (p < lim && ((*p >= 'a' && *p <= 'z') || (*p >= 'A' && *p <= 'Z') ||
               (*p >= '0' && *p <= '9') || *p == '_'))
            p++;
    }

    /* Phase 2: skip whitespace to find block opener */
    while (p < lim && (*p == ' ' || *p == '\t'))
        p++;

    if (p < lim && *p == '{') {
        /* Brace block — track depth, skip strings and comments */
        int depth = 1;
        p++;
        while (p < lim && depth > 0) {
            if (*p == '"' || *p == '\'') {
                /* Skip quoted string */
                char q = *p++;
                while (p < lim && *p != q && *p != '\n')
                    p++;
                if (p < lim && *p == q) p++;
                continue;
            }
            if (*p == '#') {
                /* Skip comment to end of line */
                while (p < lim && *p != '\n' && *p != '\0')
                    p++;
                continue;
            }
            if (*p == '{') depth++;
            else if (*p == '}') depth--;
            else if (*p == '\n') lex->line++;
            p++;
        }
    } else if (p + 1 < lim && *p == 'd' && *(p + 1) == 'o' &&
               (p + 2 >= lim || *(p + 2) == ' ' || *(p + 2) == '\n' ||
                *(p + 2) == '\t' || *(p + 2) == '\r' || *(p + 2) == '|')) {
        /* do...end block — scan for matching "end" */
        int depth = 1;
        p += 2;
        while (p < lim && depth > 0) {
            if (*p == '"' || *p == '\'') {
                /* Skip quoted string */
                char q = *p++;
                while (p < lim && *p != q && *p != '\n')
                    p++;
                if (p < lim && *p == q) p++;
                continue;
            }
            if (*p == '#') {
                /* Skip comment to end of line */
                while (p < lim && *p != '\n' && *p != '\0')
                    p++;
                continue;
            }
            if (*p == '\n') lex->line++;
            /* Check for 'end' keyword (word boundary check) */
            if (*p == 'e' && p + 2 < lim && p[1] == 'n' && p[2] == 'd' &&
                (p + 3 >= lim || p[3] == '\n' || p[3] == ' ' || p[3] == '\t' ||
                 p[3] == '\r' || p[3] == '\0')) {
                /* Verify word boundary before 'end' */
                if (p == lex->start || *(p - 1) == '\n' || *(p - 1) == ' ' ||
                    *(p - 1) == '\t') {
                    depth--;
                    if (depth == 0) { p += 3; break; }
                }
            }
            p++;
        }
    } else {
        /* No block found — consume to end of line */
        while (p < lim && *p != '\n' && *p != '\0')
            p++;
    }

    lex->cursor = p;
    token->length = (int)(lex->cursor - lex->tok);
    return GIT_SOURCE;
}

/*
 * skip_block_comment -- skip =begin ... =end block.
 *
 * Called after the lexer has matched "=begin" at column 0.
 * Advances cursor past the matching "=end" line.
 */
static void skip_block_comment(struct wow_lexer *lex)
{
    const char *p = lex->cursor;
    const char *lim = lex->limit;

    /* Skip rest of =begin line */
    while (p < lim && *p != '\n' && *p != '\0')
        p++;
    if (p < lim && *p == '\n') {
        lex->line++;
        p++;
    }

    /* Scan for =end at start of line */
    while (p < lim) {
        if (p + 4 <= lim && p[0] == '=' && p[1] == 'e' &&
            p[2] == 'n' && p[3] == 'd' &&
            (p + 4 >= lim || p[4] == '\n' || p[4] == ' ' ||
             p[4] == '\t' || p[4] == '\r' || p[4] == '\0')) {
            p += 4;
            /* Skip rest of =end line */
            while (p < lim && *p != '\n' && *p != '\0')
                p++;
            if (p < lim && *p == '\n') {
                lex->line++;
                p++;
            }
            break;
        }
        if (*p == '\n') lex->line++;
        p++;
    }

    lex->cursor = p;
}

/* ------------------------------------------------------------------ */
/* Scanner                                                             */
/* ------------------------------------------------------------------ */

int wow_lexer_scan(struct wow_lexer *lex, struct wow_token *token)
{
    for (;;) {
        lex->tok = lex->cursor;
        token->start  = lex->cursor;
        token->line   = lex->line;

        
{
	unsigned char yych;
	yych = *lex->cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '"': goto yy7;
		case '#': goto yy8;
		case '%': goto yy10;
		case '\'': goto yy11;
		case '(': goto yy12;
		case ')': goto yy13;
		case ',': goto yy14;
		case ':': goto yy15;
		case '=': goto yy16;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'o':
		case 'q':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy17;
		case '[': goto yy20;
		case ']': goto yy21;
		case 'c': goto yy22;
		case 'd': goto yy23;
		case 'e': goto yy24;
		case 'f': goto yy25;
		case 'g': goto yy26;
		case 'i': goto yy27;
		case 'n': goto yy28;
		case 'p': goto yy29;
		case 'r': goto yy30;
		case 's': goto yy31;
		case 't': goto yy32;
		case 'u': goto yy33;
		case 'w': goto yy34;
		default: goto yy2;
	}
yy1:
	++lex->cursor;
	{ token->length = 0; return 0; }
yy2:
	++lex->cursor;
yy3:
	{ token->length = 1; return ERROR; }
yy4:
	yych = *++lex->cursor;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
	{ continue; }
yy6:
	++lex->cursor;
	{
                lex->line++;
                token->length = 1;
                return NEWLINE;
            }
yy7:
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy36;
	}
yy8:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00:
		case '\n': goto yy9;
		default: goto yy8;
	}
yy9:
	{ continue; }
yy10:
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy39;
		case 'w': goto yy40;
		default: goto yy3;
	}
yy11:
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy42;
	}
yy12:
	++lex->cursor;
	{ token->length = 1; return LPAREN; }
yy13:
	++lex->cursor;
	{ token->length = 1; return RPAREN; }
yy14:
	++lex->cursor;
	{ token->length = 1; return COMMA; }
yy15:
	yych = *++lex->cursor;
	switch (yych) {
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy3;
	}
yy16:
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '>': goto yy46;
		case 'b': goto yy47;
		default: goto yy3;
	}
yy17:
	yych = *++lex->cursor;
yy18:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy17;
		case ':': goto yy48;
		default: goto yy19;
	}
yy19:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return IDENT;
            }
yy20:
	++lex->cursor;
	{ token->length = 1; return LBRACKET; }
yy21:
	++lex->cursor;
	{ token->length = 1; return RBRACKET; }
yy22:
	yych = *++lex->cursor;
	switch (yych) {
		case 'a': goto yy49;
		default: goto yy18;
	}
yy23:
	yych = *++lex->cursor;
	switch (yych) {
		case 'o': goto yy50;
		default: goto yy18;
	}
yy24:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy52;
		case 'n': goto yy53;
		case 'v': goto yy54;
		default: goto yy18;
	}
yy25:
	yych = *++lex->cursor;
	switch (yych) {
		case 'a': goto yy55;
		default: goto yy18;
	}
yy26:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy56;
		case 'i': goto yy57;
		case 'r': goto yy58;
		default: goto yy18;
	}
yy27:
	yych = *++lex->cursor;
	switch (yych) {
		case 'f': goto yy59;
		default: goto yy18;
	}
yy28:
	yych = *++lex->cursor;
	switch (yych) {
		case 'i': goto yy61;
		default: goto yy18;
	}
yy29:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy62;
		default: goto yy18;
	}
yy30:
	yych = *++lex->cursor;
	switch (yych) {
		case 'u': goto yy63;
		default: goto yy18;
	}
yy31:
	yych = *++lex->cursor;
	switch (yych) {
		case 'o': goto yy64;
		default: goto yy18;
	}
yy32:
	yych = *++lex->cursor;
	switch (yych) {
		case 'r': goto yy65;
		default: goto yy18;
	}
yy33:
	yych = *++lex->cursor;
	switch (yych) {
		case 'n': goto yy66;
		default: goto yy18;
	}
yy34:
	yych = *++lex->cursor;
	switch (yych) {
		case 'h': goto yy67;
		default: goto yy18;
	}
yy35:
	yych = *++lex->cursor;
yy36:
	switch (yych) {
		case 0x00:
		case '\n': goto yy37;
		case '"': goto yy38;
		default: goto yy35;
	}
yy37:
	lex->cursor = lex->marker;
	goto yy3;
yy38:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return STRING;
            }
yy39:
	yych = *++lex->cursor;
	switch (yych) {
		case '[': goto yy68;
		default: goto yy37;
	}
yy40:
	yych = *++lex->cursor;
	switch (yych) {
		case '[': goto yy69;
		default: goto yy37;
	}
yy41:
	yych = *++lex->cursor;
yy42:
	switch (yych) {
		case 0x00:
		case '\n': goto yy37;
		case '\'': goto yy43;
		default: goto yy41;
	}
yy43:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return STRING;
            }
yy44:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy45;
	}
yy45:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return SYMBOL;
            }
yy46:
	++lex->cursor;
	{ token->length = 2; return HASHROCKET; }
yy47:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy70;
		default: goto yy37;
	}
yy48:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return KEY;
            }
yy49:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy71;
		default: goto yy18;
	}
yy50:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy51;
	}
yy51:
	{ token->length = 2;  return DO; }
yy52:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy72;
		default: goto yy18;
	}
yy53:
	yych = *++lex->cursor;
	switch (yych) {
		case 'd': goto yy73;
		default: goto yy18;
	}
yy54:
	yych = *++lex->cursor;
	switch (yych) {
		case 'a': goto yy75;
		default: goto yy18;
	}
yy55:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy76;
		default: goto yy18;
	}
yy56:
	yych = *++lex->cursor;
	switch (yych) {
		case 'm': goto yy77;
		default: goto yy18;
	}
yy57:
	yych = *++lex->cursor;
	switch (yych) {
		case 't': goto yy79;
		default: goto yy18;
	}
yy58:
	yych = *++lex->cursor;
	switch (yych) {
		case 'o': goto yy80;
		default: goto yy18;
	}
yy59:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy60;
	}
yy60:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy61:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy81;
		default: goto yy18;
	}
yy62:
	yych = *++lex->cursor;
	switch (yych) {
		case 'a': goto yy83;
		case 'u': goto yy84;
		default: goto yy18;
	}
yy63:
	yych = *++lex->cursor;
	switch (yych) {
		case 'b': goto yy85;
		default: goto yy18;
	}
yy64:
	yych = *++lex->cursor;
	switch (yych) {
		case 'u': goto yy86;
		default: goto yy18;
	}
yy65:
	yych = *++lex->cursor;
	switch (yych) {
		case 'u': goto yy87;
		default: goto yy18;
	}
yy66:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy88;
		default: goto yy18;
	}
yy67:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy89;
		default: goto yy18;
	}
yy68:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00: goto yy37;
		case ']': goto yy90;
		default: goto yy68;
	}
yy69:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00: goto yy37;
		case ']': goto yy91;
		default: goto yy69;
	}
yy70:
	yych = *++lex->cursor;
	switch (yych) {
		case 'g': goto yy92;
		default: goto yy37;
	}
yy71:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy93;
		default: goto yy18;
	}
yy72:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy95;
		case 'i': goto yy97;
		default: goto yy18;
	}
yy73:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy74;
	}
yy74:
	{ token->length = 3;  return END; }
yy75:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy98;
		default: goto yy18;
	}
yy76:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy100;
		default: goto yy18;
	}
yy77:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 's': goto yy101;
		default: goto yy78;
	}
yy78:
	{ token->length = 3;  return GEM; }
yy79:
	yych = *++lex->cursor;
	switch (yych) {
		case '_': goto yy102;
		default: goto yy18;
	}
yy80:
	yych = *++lex->cursor;
	switch (yych) {
		case 'u': goto yy103;
		default: goto yy18;
	}
yy81:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy82;
	}
yy82:
	{ token->length = 3;  return LIT_NIL; }
yy83:
	yych = *++lex->cursor;
	switch (yych) {
		case 't': goto yy104;
		default: goto yy18;
	}
yy84:
	yych = *++lex->cursor;
	switch (yych) {
		case 'g': goto yy105;
		default: goto yy18;
	}
yy85:
	yych = *++lex->cursor;
	switch (yych) {
		case 'y': goto yy106;
		default: goto yy18;
	}
yy86:
	yych = *++lex->cursor;
	switch (yych) {
		case 'r': goto yy108;
		default: goto yy18;
	}
yy87:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy109;
		default: goto yy18;
	}
yy88:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy111;
		default: goto yy18;
	}
yy89:
	yych = *++lex->cursor;
	switch (yych) {
		case 'n': goto yy112;
		default: goto yy18;
	}
yy90:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return PERCENT_ARRAY;
            }
yy91:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return PERCENT_ARRAY;
            }
yy92:
	yych = *++lex->cursor;
	switch (yych) {
		case 'i': goto yy114;
		default: goto yy37;
	}
yy93:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy94;
	}
yy94:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy95:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy96;
	}
yy96:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy97:
	yych = *++lex->cursor;
	switch (yych) {
		case 'f': goto yy115;
		default: goto yy18;
	}
yy98:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case '_': goto yy117;
		default: goto yy99;
	}
yy99:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy100:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy118;
		default: goto yy18;
	}
yy101:
	yych = *++lex->cursor;
	switch (yych) {
		case 'p': goto yy120;
		default: goto yy18;
	}
yy102:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy121;
		default: goto yy18;
	}
yy103:
	yych = *++lex->cursor;
	switch (yych) {
		case 'p': goto yy122;
		default: goto yy18;
	}
yy104:
	yych = *++lex->cursor;
	switch (yych) {
		case 'f': goto yy124;
		default: goto yy18;
	}
yy105:
	yych = *++lex->cursor;
	switch (yych) {
		case 'i': goto yy125;
		default: goto yy18;
	}
yy106:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy107;
	}
yy107:
	{ token->length = 4;  return RUBY; }
yy108:
	yych = *++lex->cursor;
	switch (yych) {
		case 'c': goto yy126;
		default: goto yy18;
	}
yy109:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy110;
	}
yy110:
	{ token->length = 4;  return LIT_TRUE; }
yy111:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy127;
		default: goto yy18;
	}
yy112:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy113;
	}
yy113:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy114:
	yych = *++lex->cursor;
	switch (yych) {
		case 'n': goto yy128;
		default: goto yy37;
	}
yy115:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy116;
	}
yy116:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy117:
	yych = *++lex->cursor;
	switch (yych) {
		case 'g': goto yy129;
		default: goto yy18;
	}
yy118:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy119;
	}
yy119:
	{ token->length = 5;  return LIT_FALSE; }
yy120:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy130;
		default: goto yy18;
	}
yy121:
	yych = *++lex->cursor;
	switch (yych) {
		case 'o': goto yy131;
		default: goto yy18;
	}
yy122:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy123;
	}
yy123:
	{ token->length = 5;  return GROUP; }
yy124:
	yych = *++lex->cursor;
	switch (yych) {
		case 'o': goto yy132;
		default: goto yy18;
	}
yy125:
	yych = *++lex->cursor;
	switch (yych) {
		case 'n': goto yy133;
		default: goto yy18;
	}
yy126:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy135;
		default: goto yy18;
	}
yy127:
	yych = *++lex->cursor;
	switch (yych) {
		case 's': goto yy137;
		default: goto yy18;
	}
yy128:
	++lex->cursor;
	{
                if (lex->tok == lex->start ||
                    (lex->tok > lex->start && *(lex->tok - 1) == '\n')) {
                    skip_block_comment(lex);
                    continue;
                }
                /* Not at column 0 — treat as identifier */
                token->length = (int)(lex->cursor - lex->tok);
                return IDENT;
            }
yy129:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy139;
		default: goto yy18;
	}
yy130:
	yych = *++lex->cursor;
	switch (yych) {
		case 'c': goto yy140;
		default: goto yy18;
	}
yy131:
	yych = *++lex->cursor;
	switch (yych) {
		case 'u': goto yy142;
		default: goto yy18;
	}
yy132:
	yych = *++lex->cursor;
	switch (yych) {
		case 'r': goto yy143;
		default: goto yy18;
	}
yy133:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy134;
	}
yy134:
	{ token->length = 6;  return PLUGIN; }
yy135:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy136;
	}
yy136:
	{ token->length = 6;  return SOURCE; }
yy137:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy138;
	}
yy138:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy139:
	yych = *++lex->cursor;
	switch (yych) {
		case 'm': goto yy144;
		default: goto yy18;
	}
yy140:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy141;
	}
yy141:
	{ token->length = 7;  return GEMSPEC; }
yy142:
	yych = *++lex->cursor;
	switch (yych) {
		case 'r': goto yy145;
		default: goto yy18;
	}
yy143:
	yych = *++lex->cursor;
	switch (yych) {
		case 'm': goto yy146;
		default: goto yy18;
	}
yy144:
	yych = *++lex->cursor;
	switch (yych) {
		case 'f': goto yy148;
		default: goto yy18;
	}
yy145:
	yych = *++lex->cursor;
	switch (yych) {
		case 'c': goto yy149;
		default: goto yy18;
	}
yy146:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		case 's': goto yy150;
		default: goto yy147;
	}
yy147:
	{ token->length = 8;  return PLATFORMS; }
yy148:
	yych = *++lex->cursor;
	switch (yych) {
		case 'i': goto yy152;
		default: goto yy18;
	}
yy149:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy153;
		default: goto yy18;
	}
yy150:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy151;
	}
yy151:
	{ token->length = 9;  return PLATFORMS; }
yy152:
	yych = *++lex->cursor;
	switch (yych) {
		case 'l': goto yy155;
		default: goto yy18;
	}
yy153:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy154;
	}
yy154:
	{
                return skip_git_source_block(lex, token);
            }
yy155:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy156;
		default: goto yy18;
	}
yy156:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy18;
		default: goto yy157;
	}
yy157:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
}

    }
}
