/* Generated by re2c 3.1 on Tue Feb 17 21:26:05 2026 */
/*
 * lexer.re -- re2c input for Gemfile lexer
 *
 * Tokenises a restricted subset of Gemfile syntax.
 * Token IDs come from the lemon-generated parser.h.
 *
 * Generate: re2c -o src/gemfile/lexer.c src/gemfile/lexer.re --no-debug-info
 */

#include <string.h>
#include "wow/gemfile/lexer.h"
#include "parser.h"

void wow_lexer_init(struct wow_lexer *lex, const char *buf, int len)
{
    lex->cursor = buf;
    lex->limit  = buf + len;
    lex->marker = buf;
    lex->tok    = buf;
    lex->start  = buf;
    lex->line   = 1;
}

/* ------------------------------------------------------------------ */
/* Helpers for multi-line skip patterns                                */
/* ------------------------------------------------------------------ */

/*
 * skip_git_source_block -- consume a git_source(...) { ... } declaration.
 *
 * Called after the lexer has matched "git_source". Advances the cursor
 * past the entire declaration including its block body.
 *
 * Handles:
 *   git_source(:github) { |repo| "https://github.com/#{repo}.git" }
 *   git_source(:github) do |repo|
 *     "https://github.com/#{repo}"
 *   end
 *   git_source :github do |repo| ... end
 */
static int skip_git_source_block(struct wow_lexer *lex, struct wow_token *token)
{
    const char *p = lex->cursor;
    const char *lim = lex->limit;

    /* Phase 1: skip optional (args) or bare :symbol */
    while (p < lim && (*p == ' ' || *p == '\t'))
        p++;
    if (p < lim && *p == '(') {
        p++;
        while (p < lim && *p != ')')
            p++;
        if (p < lim) p++;  /* skip ')' */
    } else if (p < lim && *p == ':') {
        p++;
        while (p < lim && ((*p >= 'a' && *p <= 'z') || (*p >= 'A' && *p <= 'Z') ||
               (*p >= '0' && *p <= '9') || *p == '_'))
            p++;
    }

    /* Phase 2: skip whitespace to find block opener */
    while (p < lim && (*p == ' ' || *p == '\t'))
        p++;

    if (p < lim && *p == '{') {
        /* Brace block — track depth, skip strings and comments */
        int depth = 1;
        p++;
        while (p < lim && depth > 0) {
            if (*p == '"' || *p == '\'') {
                /* Skip quoted string */
                char q = *p++;
                while (p < lim && *p != q && *p != '\n')
                    p++;
                if (p < lim && *p == q) p++;
                continue;
            }
            if (*p == '#') {
                /* Skip comment to end of line */
                while (p < lim && *p != '\n' && *p != '\0')
                    p++;
                continue;
            }
            if (*p == '{') depth++;
            else if (*p == '}') depth--;
            else if (*p == '\n') lex->line++;
            p++;
        }
    } else if (p + 1 < lim && *p == 'd' && *(p + 1) == 'o' &&
               (p + 2 >= lim || *(p + 2) == ' ' || *(p + 2) == '\n' ||
                *(p + 2) == '\t' || *(p + 2) == '\r' || *(p + 2) == '|')) {
        /* do...end block — scan for matching "end" */
        int depth = 1;
        p += 2;
        while (p < lim && depth > 0) {
            if (*p == '"' || *p == '\'') {
                /* Skip quoted string */
                char q = *p++;
                while (p < lim && *p != q && *p != '\n')
                    p++;
                if (p < lim && *p == q) p++;
                continue;
            }
            if (*p == '#') {
                /* Skip comment to end of line */
                while (p < lim && *p != '\n' && *p != '\0')
                    p++;
                continue;
            }
            if (*p == '\n') lex->line++;
            /* Check for 'end' keyword (word boundary check) */
            if (*p == 'e' && p + 2 < lim && p[1] == 'n' && p[2] == 'd' &&
                (p + 3 >= lim || p[3] == '\n' || p[3] == ' ' || p[3] == '\t' ||
                 p[3] == '\r' || p[3] == '\0')) {
                /* Verify word boundary before 'end' */
                if (p == lex->start || *(p - 1) == '\n' || *(p - 1) == ' ' ||
                    *(p - 1) == '\t') {
                    depth--;
                    if (depth == 0) { p += 3; break; }
                }
            }
            p++;
        }
    } else {
        /* No block found — consume to end of line */
        while (p < lim && *p != '\n' && *p != '\0')
            p++;
    }

    lex->cursor = p;
    token->length = (int)(lex->cursor - lex->tok);
    return GIT_SOURCE;
}

/*
 * skip_block_comment -- skip =begin ... =end block.
 *
 * Called after the lexer has matched "=begin" at column 0.
 * Advances cursor past the matching "=end" line.
 */
static void skip_block_comment(struct wow_lexer *lex)
{
    const char *p = lex->cursor;
    const char *lim = lex->limit;

    /* Skip rest of =begin line */
    while (p < lim && *p != '\n' && *p != '\0')
        p++;
    if (p < lim && *p == '\n') {
        lex->line++;
        p++;
    }

    /* Scan for =end at start of line */
    while (p < lim) {
        if (p + 4 <= lim && p[0] == '=' && p[1] == 'e' &&
            p[2] == 'n' && p[3] == 'd' &&
            (p + 4 >= lim || p[4] == '\n' || p[4] == ' ' ||
             p[4] == '\t' || p[4] == '\r' || p[4] == '\0')) {
            p += 4;
            /* Skip rest of =end line */
            while (p < lim && *p != '\n' && *p != '\0')
                p++;
            if (p < lim && *p == '\n') {
                lex->line++;
                p++;
            }
            break;
        }
        if (*p == '\n') lex->line++;
        p++;
    }

    lex->cursor = p;
}

/* ------------------------------------------------------------------ */
/* Scanner                                                             */
/* ------------------------------------------------------------------ */

int wow_lexer_scan(struct wow_lexer *lex, struct wow_token *token)
{
    for (;;) {
        lex->tok = lex->cursor;
        token->start  = lex->cursor;
        token->line   = lex->line;

        
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *lex->cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '!': goto yy7;
		case '"': goto yy9;
		case '#': goto yy10;
		case '%': goto yy12;
		case '&': goto yy13;
		case '\'': goto yy14;
		case '(': goto yy15;
		case ')': goto yy16;
		case ',': goto yy17;
		case '.': goto yy18;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		case ':': goto yy21;
		case '<': goto yy22;
		case '=': goto yy24;
		case '>': goto yy26;
		case '?': goto yy28;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'o':
		case 'q':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case '[': goto yy32;
		case ']': goto yy33;
		case 'c': goto yy34;
		case 'd': goto yy35;
		case 'e': goto yy36;
		case 'f': goto yy37;
		case 'g': goto yy38;
		case 'i': goto yy39;
		case 'n': goto yy40;
		case 'p': goto yy41;
		case 'r': goto yy42;
		case 's': goto yy43;
		case 't': goto yy44;
		case 'u': goto yy45;
		case 'w': goto yy46;
		case '|': goto yy47;
		default: goto yy2;
	}
yy1:
	++lex->cursor;
	{ token->length = 0; return 0; }
yy2:
	++lex->cursor;
yy3:
	{ token->length = 1; return ERROR; }
yy4:
	yych = *++lex->cursor;
	switch (yych) {
		case '\t':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
	{ continue; }
yy6:
	++lex->cursor;
	{
                lex->line++;
                token->length = 1;
                return NEWLINE;
            }
yy7:
	yych = *++lex->cursor;
	switch (yych) {
		case '=': goto yy49;
		default: goto yy8;
	}
yy8:
	{ token->length = 1; return BANG; }
yy9:
	yyaccept = 0;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy51;
	}
yy10:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00:
		case '\n': goto yy11;
		default: goto yy10;
	}
yy11:
	{ continue; }
yy12:
	yyaccept = 0;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy54;
		case 'w': goto yy55;
		default: goto yy3;
	}
yy13:
	yych = *++lex->cursor;
	switch (yych) {
		case '&': goto yy56;
		default: goto yy3;
	}
yy14:
	yyaccept = 0;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 0x00:
		case '\n': goto yy3;
		default: goto yy58;
	}
yy15:
	++lex->cursor;
	{ token->length = 1; return LPAREN; }
yy16:
	++lex->cursor;
	{ token->length = 1; return RPAREN; }
yy17:
	++lex->cursor;
	{ token->length = 1; return COMMA; }
yy18:
	++lex->cursor;
	{ token->length = 1; return DOT; }
yy19:
	yyaccept = 1;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '.': goto yy60;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy19;
		default: goto yy20;
	}
yy20:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return INTEGER;
            }
yy21:
	yych = *++lex->cursor;
	switch (yych) {
		case ':': goto yy61;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy62;
		default: goto yy3;
	}
yy22:
	yych = *++lex->cursor;
	switch (yych) {
		case '=': goto yy64;
		default: goto yy23;
	}
yy23:
	{ token->length = 1; return LT; }
yy24:
	yyaccept = 2;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '=': goto yy65;
		case '>': goto yy66;
		case 'b': goto yy67;
		case '~': goto yy68;
		default: goto yy25;
	}
yy25:
	{ token->length = 1; return ASSIGN; }
yy26:
	yych = *++lex->cursor;
	switch (yych) {
		case '=': goto yy69;
		default: goto yy27;
	}
yy27:
	{ token->length = 1; return GT; }
yy28:
	++lex->cursor;
	{ token->length = 1; return QUESTION; }
yy29:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
yy30:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case ':': goto yy70;
		default: goto yy31;
	}
yy31:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return IDENT;
            }
yy32:
	++lex->cursor;
	{ token->length = 1; return LBRACKET; }
yy33:
	++lex->cursor;
	{ token->length = 1; return RBRACKET; }
yy34:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'a': goto yy71;
		default: goto yy30;
	}
yy35:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy72;
		case 'o': goto yy73;
		default: goto yy30;
	}
yy36:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy75;
		case 'n': goto yy76;
		case 'v': goto yy77;
		default: goto yy30;
	}
yy37:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'a': goto yy78;
		default: goto yy30;
	}
yy38:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy79;
		case 'i': goto yy80;
		case 'r': goto yy81;
		default: goto yy30;
	}
yy39:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'f': goto yy82;
		default: goto yy30;
	}
yy40:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy84;
		default: goto yy30;
	}
yy41:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy85;
		default: goto yy30;
	}
yy42:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy86;
		case 'u': goto yy87;
		default: goto yy30;
	}
yy43:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'o': goto yy88;
		default: goto yy30;
	}
yy44:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'r': goto yy89;
		default: goto yy30;
	}
yy45:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'n': goto yy90;
		default: goto yy30;
	}
yy46:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'h': goto yy91;
		default: goto yy30;
	}
yy47:
	yych = *++lex->cursor;
	switch (yych) {
		case '|': goto yy92;
		default: goto yy48;
	}
yy48:
	{ token->length = 1; return PIPE; }
yy49:
	++lex->cursor;
	{ token->length = 2; return NEQ; }
yy50:
	yych = *++lex->cursor;
yy51:
	switch (yych) {
		case 0x00:
		case '\n': goto yy52;
		case '"': goto yy53;
		default: goto yy50;
	}
yy52:
	lex->cursor = lex->marker;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy20;
		case 2: goto yy25;
		case 3: goto yy31;
		case 4: goto yy74;
		case 5: goto yy83;
		case 6: goto yy101;
		case 7: goto yy104;
		case 8: goto yy108;
		case 9: goto yy112;
		case 10: goto yy125;
		case 11: goto yy127;
		case 12: goto yy130;
		case 13: goto yy139;
		case 14: goto yy142;
		case 15: goto yy145;
		case 16: goto yy148;
		case 17: goto yy151;
		case 18: goto yy155;
		case 19: goto yy167;
		case 20: goto yy170;
		case 21: goto yy172;
		case 22: goto yy175;
		case 23: goto yy179;
		case 24: goto yy183;
		case 25: goto yy187;
		case 26: goto yy190;
		default: goto yy193;
	}
yy53:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return STRING;
            }
yy54:
	yych = *++lex->cursor;
	switch (yych) {
		case '[': goto yy93;
		default: goto yy52;
	}
yy55:
	yych = *++lex->cursor;
	switch (yych) {
		case '[': goto yy94;
		default: goto yy52;
	}
yy56:
	++lex->cursor;
	{ token->length = 2; return AND; }
yy57:
	yych = *++lex->cursor;
yy58:
	switch (yych) {
		case 0x00:
		case '\n': goto yy52;
		case '\'': goto yy59;
		default: goto yy57;
	}
yy59:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return STRING;
            }
yy60:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy95;
		default: goto yy52;
	}
yy61:
	++lex->cursor;
	{ token->length = 2; return COLON_COLON; }
yy62:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy62;
		default: goto yy63;
	}
yy63:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return SYMBOL;
            }
yy64:
	++lex->cursor;
	{ token->length = 2; return LTE; }
yy65:
	++lex->cursor;
	{ token->length = 2; return EQ; }
yy66:
	++lex->cursor;
	{ token->length = 2; return HASHROCKET; }
yy67:
	yych = *++lex->cursor;
	switch (yych) {
		case 'e': goto yy97;
		default: goto yy52;
	}
yy68:
	++lex->cursor;
	{ token->length = 2; return MATCH; }
yy69:
	++lex->cursor;
	{ token->length = 2; return GTE; }
yy70:
	yych = *++lex->cursor;
	switch (yych) {
		case ':': goto yy52;
		default: goto yy98;
	}
yy71:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy99;
		default: goto yy30;
	}
yy72:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'f': goto yy100;
		default: goto yy30;
	}
yy73:
	yyaccept = 4;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy74;
	}
yy74:
	{ token->length = 2;  return DO; }
yy75:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy102;
		default: goto yy30;
	}
yy76:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'd': goto yy103;
		default: goto yy30;
	}
yy77:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'a': goto yy105;
		default: goto yy30;
	}
yy78:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy106;
		default: goto yy30;
	}
yy79:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'm': goto yy107;
		default: goto yy30;
	}
yy80:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 't': goto yy109;
		default: goto yy30;
	}
yy81:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'o': goto yy110;
		default: goto yy30;
	}
yy82:
	yyaccept = 5;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy83;
	}
yy83:
	{ token->length = 2;  return IF; }
yy84:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy111;
		default: goto yy30;
	}
yy85:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'a': goto yy113;
		case 'u': goto yy114;
		default: goto yy30;
	}
yy86:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'q': goto yy115;
		default: goto yy30;
	}
yy87:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'b': goto yy116;
		default: goto yy30;
	}
yy88:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'u': goto yy117;
		default: goto yy30;
	}
yy89:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'u': goto yy118;
		default: goto yy30;
	}
yy90:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy119;
		default: goto yy30;
	}
yy91:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy120;
		default: goto yy30;
	}
yy92:
	++lex->cursor;
	{ token->length = 2; return OR; }
yy93:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00: goto yy52;
		case ']': goto yy121;
		default: goto yy93;
	}
yy94:
	yych = *++lex->cursor;
	switch (yych) {
		case 0x00: goto yy52;
		case ']': goto yy122;
		default: goto yy94;
	}
yy95:
	yych = *++lex->cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy95;
		default: goto yy96;
	}
yy96:
	{
                token->length = (int)(lex->cursor - lex->tok);
                return FLOAT_LIT;
            }
yy97:
	yych = *++lex->cursor;
	switch (yych) {
		case 'g': goto yy123;
		default: goto yy52;
	}
yy98:
	++lex->cursor;
	lex->cursor -= 1;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return KEY;
            }
yy99:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy124;
		default: goto yy30;
	}
yy100:
	yyaccept = 6;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy101;
	}
yy101:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy102:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy126;
		case 'i': goto yy128;
		default: goto yy30;
	}
yy103:
	yyaccept = 7;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy104;
	}
yy104:
	{ token->length = 3;  return END; }
yy105:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy129;
		default: goto yy30;
	}
yy106:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy131;
		default: goto yy30;
	}
yy107:
	yyaccept = 8;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		case 's': goto yy132;
		default: goto yy108;
	}
yy108:
	{ token->length = 3;  return GEM; }
yy109:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '_': goto yy133;
		default: goto yy30;
	}
yy110:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'u': goto yy134;
		default: goto yy30;
	}
yy111:
	yyaccept = 9;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy112;
	}
yy112:
	{ token->length = 3;  return LIT_NIL; }
yy113:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 't': goto yy135;
		default: goto yy30;
	}
yy114:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'g': goto yy136;
		default: goto yy30;
	}
yy115:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'u': goto yy137;
		default: goto yy30;
	}
yy116:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'y': goto yy138;
		default: goto yy30;
	}
yy117:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'r': goto yy140;
		default: goto yy30;
	}
yy118:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy141;
		default: goto yy30;
	}
yy119:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy143;
		default: goto yy30;
	}
yy120:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'n': goto yy144;
		default: goto yy30;
	}
yy121:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return PERCENT_ARRAY;
            }
yy122:
	++lex->cursor;
	{
                token->length = (int)(lex->cursor - lex->tok);
                return PERCENT_ARRAY;
            }
yy123:
	yych = *++lex->cursor;
	switch (yych) {
		case 'i': goto yy146;
		default: goto yy52;
	}
yy124:
	yyaccept = 10;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy125;
	}
yy125:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy126:
	yyaccept = 11;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy127;
	}
yy127:
	{ token->length = 4;  return ELSE; }
yy128:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'f': goto yy147;
		default: goto yy30;
	}
yy129:
	yyaccept = 12;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		case '_': goto yy149;
		default: goto yy130;
	}
yy130:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy131:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy150;
		default: goto yy30;
	}
yy132:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'p': goto yy152;
		default: goto yy30;
	}
yy133:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy153;
		default: goto yy30;
	}
yy134:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'p': goto yy154;
		default: goto yy30;
	}
yy135:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'f': goto yy156;
		default: goto yy30;
	}
yy136:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy157;
		default: goto yy30;
	}
yy137:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy158;
		default: goto yy30;
	}
yy138:
	yyaccept = 13;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy139;
	}
yy139:
	{ token->length = 4;  return RUBY; }
yy140:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'c': goto yy159;
		default: goto yy30;
	}
yy141:
	yyaccept = 14;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy142;
	}
yy142:
	{ token->length = 4;  return LIT_TRUE; }
yy143:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy160;
		default: goto yy30;
	}
yy144:
	yyaccept = 15;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy145;
	}
yy145:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy146:
	yych = *++lex->cursor;
	switch (yych) {
		case 'n': goto yy161;
		default: goto yy52;
	}
yy147:
	yyaccept = 16;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy148;
	}
yy148:
	{ token->length = 5;  return ELSIF; }
yy149:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'g': goto yy162;
		default: goto yy30;
	}
yy150:
	yyaccept = 17;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy151;
	}
yy151:
	{ token->length = 5;  return LIT_FALSE; }
yy152:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy163;
		default: goto yy30;
	}
yy153:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'o': goto yy164;
		default: goto yy30;
	}
yy154:
	yyaccept = 18;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy155;
	}
yy155:
	{ token->length = 5;  return GROUP; }
yy156:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'o': goto yy165;
		default: goto yy30;
	}
yy157:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'n': goto yy166;
		default: goto yy30;
	}
yy158:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'r': goto yy168;
		default: goto yy30;
	}
yy159:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy169;
		default: goto yy30;
	}
yy160:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 's': goto yy171;
		default: goto yy30;
	}
yy161:
	++lex->cursor;
	{
                if (lex->tok == lex->start ||
                    (lex->tok > lex->start && *(lex->tok - 1) == '\n')) {
                    skip_block_comment(lex);
                    continue;
                }
                /* Not at column 0 — treat as identifier */
                token->length = (int)(lex->cursor - lex->tok);
                return IDENT;
            }
yy162:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy173;
		default: goto yy30;
	}
yy163:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'c': goto yy174;
		default: goto yy30;
	}
yy164:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'u': goto yy176;
		default: goto yy30;
	}
yy165:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'r': goto yy177;
		default: goto yy30;
	}
yy166:
	yyaccept = 19;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy167;
	}
yy167:
	{ token->length = 6;  return PLUGIN; }
yy168:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy178;
		default: goto yy30;
	}
yy169:
	yyaccept = 20;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy170;
	}
yy170:
	{ token->length = 6;  return SOURCE; }
yy171:
	yyaccept = 21;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy172;
	}
yy172:
	{ token->length = 6;  return UNLESS; }
yy173:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'm': goto yy180;
		default: goto yy30;
	}
yy174:
	yyaccept = 22;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy175;
	}
yy175:
	{ token->length = 7;  return GEMSPEC; }
yy176:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'r': goto yy181;
		default: goto yy30;
	}
yy177:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'm': goto yy182;
		default: goto yy30;
	}
yy178:
	yyaccept = 23;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy179;
	}
yy179:
	{ token->length = (int)(lex->cursor - lex->tok); return UNSUPPORTED; }
yy180:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'f': goto yy184;
		default: goto yy30;
	}
yy181:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'c': goto yy185;
		default: goto yy30;
	}
yy182:
	yyaccept = 24;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		case 's': goto yy186;
		default: goto yy183;
	}
yy183:
	{ token->length = 8;  return PLATFORMS; }
yy184:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'i': goto yy188;
		default: goto yy30;
	}
yy185:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy189;
		default: goto yy30;
	}
yy186:
	yyaccept = 25;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy187;
	}
yy187:
	{ token->length = 9;  return PLATFORMS; }
yy188:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'l': goto yy191;
		default: goto yy30;
	}
yy189:
	yyaccept = 26;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy190;
	}
yy190:
	{
                return skip_git_source_block(lex, token);
            }
yy191:
	yyaccept = 3;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case 'e': goto yy192;
		default: goto yy30;
	}
yy192:
	yyaccept = 27;
	yych = *(lex->marker = ++lex->cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy193;
	}
yy193:
	{ token->length = 12; return EVAL_GEMFILE; }
}

    }
}
