/* This file is automatically generated by Lemon from input grammar
** source file "src/gemfile/parser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 11 "src/gemfile/parser.y"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "wow/gemfile/lexer.h"
#include "wow/gemfile/types.h"

/*
 * Helper: duplicate a token's text, stripping leading/trailing chars.
 * strip_left/strip_right indicate how many chars to remove from each end.
 * For STRING tokens: strip 1 from each side (the quotes).
 * For SYMBOL tokens: strip 1 from left (the colon).
 * For KEY tokens: strip 1 from right (the colon).
 */
static char *tok_strdup(struct wow_token t, int strip_left, int strip_right)
{
    int len = t.length - strip_left - strip_right;
    if (len <= 0) return strdup("");
    return strndup(t.start + strip_left, (size_t)len);
}

/*
 * Accumulator for gem_opts: collects version constraints + keyword
 * options as the parser reduces gem_opts rules left-to-right.
 */
struct gem_opts_acc {
    char **constraints;
    int    n_constraints;
    int    constraints_cap;
    char **groups;
    int    n_groups;
    int    groups_cap;
    char **autorequire;
    int    n_autorequire;
    int    autorequire_cap;
    bool   autorequire_specified;
    char **platforms;
    int    n_platforms;
    int    platforms_cap;
};

static void gem_opts_acc_init(struct gem_opts_acc *a)
{
    memset(a, 0, sizeof(*a));
}

static void gem_opts_acc_add_constraint(struct gem_opts_acc *a, char *s)
{
    if (a->n_constraints >= a->constraints_cap) {
        a->constraints_cap = a->constraints_cap ? a->constraints_cap * 2 : 4;
        a->constraints = realloc(a->constraints,
                                 sizeof(char *) * (size_t)a->constraints_cap);
    }
    a->constraints[a->n_constraints++] = s;
}

static void gem_opts_acc_add_string(char ***arr, int *n, int *cap, char *s)
{
    if (*n >= *cap) {
        *cap = *cap ? *cap * 2 : 4;
        *arr = realloc(*arr, sizeof(char *) * (size_t)*cap);
    }
    (*arr)[(*n)++] = s;
}

/*
 * Parse a %w[...] or %i[...] token into individual whitespace-separated items.
 * Token format: "%w[foo bar baz]" or "%i[mri windows]" or with () delimiters.
 * Items are stored in acc->groups[] (generic string array).
 */
static void parse_percent_array(struct gem_opts_acc *acc, struct wow_token t)
{
    gem_opts_acc_init(acc);
    /* Skip "%w[" or "%i[" or "%w(" or "%i(" prefix (3 chars)
     * and trailing "]" or ")" (1 char) */
    if (t.length < 4) return;
    const char *p = t.start + 3;
    const char *end = t.start + t.length - 1;
    while (p < end) {
        /* Skip whitespace */
        while (p < end && (*p == ' ' || *p == '\t' || *p == '\n')) p++;
        if (p >= end) break;
        /* Find end of item */
        const char *item_start = p;
        while (p < end && *p != ' ' && *p != '\t' && *p != '\n') p++;
        int len = (int)(p - item_start);
        if (len > 0) {
            gem_opts_acc_add_string(&acc->groups, &acc->n_groups,
                                    &acc->groups_cap,
                                    strndup(item_start, (size_t)len));
        }
    }
}

static void gem_opts_acc_free(struct gem_opts_acc *a)
{
    int i;
    for (i = 0; i < a->n_constraints; i++)
        free(a->constraints[i]);
    free(a->constraints);
    for (i = 0; i < a->n_groups; i++)
        free(a->groups[i]);
    free(a->groups);
    for (i = 0; i < a->n_autorequire; i++)
        free(a->autorequire[i]);
    free(a->autorequire);
    for (i = 0; i < a->n_platforms; i++)
        free(a->platforms[i]);
    free(a->platforms);
}

#line 144 "src/gemfile/parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef SOURCE
#define SOURCE                          1
#define GEM                             2
#define GROUP                           3
#define DO                              4
#define END                             5
#define RUBY                            6
#define GEMSPEC                         7
#define LIT_TRUE                        8
#define LIT_FALSE                       9
#define LIT_NIL                        10
#define STRING                         11
#define SYMBOL                         12
#define KEY                            13
#define COMMA                          14
#define HASHROCKET                     15
#define NEWLINE                        16
#define IDENT                          17
#define UNSUPPORTED                    18
#define ERROR                          19
#define GIT_SOURCE                     20
#define PLUGIN                         21
#define PLATFORMS                      22
#define PATH                           23
#define GIT                            24
#define GITHUB                         25
#define INSTALL_IF                     26
#define LBRACKET                       27
#define RBRACKET                       28
#define LPAREN                         29
#define RPAREN                         30
#define PERCENT_ARRAY                  31
#define IF                             32
#define UNLESS                         33
#define ELSE                           34
#define ELSIF                          35
#define EVAL_GEMFILE                   36
#define EQ                             37
#define NEQ                            38
#define GTE                            39
#define LTE                            40
#define GT                             41
#define LT                             42
#define MATCH                          43
#define AND                            44
#define OR                             45
#define BANG                           46
#define ASSIGN                         47
#define DOT                            48
#define COLON_COLON                    49
#define PIPE                           50
#define QUESTION                       51
#define INTEGER                        52
#define FLOAT_LIT                      53
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 80
#define YYACTIONTYPE unsigned short int
#define ParseTOKENTYPE  struct wow_token 
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  struct gem_opts_acc yy50;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  struct wow_gemfile *gf ;
#define ParseARG_PDECL , struct wow_gemfile *gf 
#define ParseARG_PARAM ,gf 
#define ParseARG_FETCH  struct wow_gemfile *gf =yypParser->gf ;
#define ParseARG_STORE yypParser->gf =gf ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             76
#define YYNRULE              90
#define YYNRULE_WITH_ACTION  50
#define YYNTOKEN             54
#define YY_MAX_SHIFT         75
#define YY_MIN_SHIFTREDUCE   155
#define YY_MAX_SHIFTREDUCE   244
#define YY_ERROR_ACTION      245
#define YY_ACCEPT_ACTION     246
#define YY_NO_ACTION         247
#define YY_MIN_REDUCE        248
#define YY_MAX_REDUCE        337
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (256)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   267,   34,   53,   12,  261,  233,   42,   14,  246,    8,
 /*    10 */   228,  229,  269,  226,  227,   48,  220,  193,  192,   32,
 /*    20 */   219,   58,   16,   68,   66,   65,   64,  299,  299,  299,
 /*    30 */   299,  299,  299,  299,  299,  299,  299,  299,  299,   59,
 /*    40 */    36,   27,  203,   26,   40,   34,   53,   12,   52,  232,
 /*    50 */    42,   14,  191,  190,   47,  170,  169,  171,  173,  172,
 /*    60 */   220,  191,  190,   61,  219,   58,   16,   68,   66,   65,
 /*    70 */    64,   34,   53,   12,   13,  231,   42,   14,  182,   15,
 /*    80 */   196,  164,  163,  165,  167,  166,  220,  239,  240,   29,
 /*    90 */   219,   58,   16,   68,   66,   65,   64,   34,   53,   12,
 /*   100 */    13,  230,   42,   14,  182,  221,  222,   71,  223,  224,
 /*   110 */   237,  238,  220,  184,  183,   46,  219,   58,   16,   68,
 /*   120 */    66,   65,   64,   34,   53,   12,  178,  195,   42,   14,
 /*   130 */   181,  241,  242,    1,   75,  156,  235,  236,  220,   50,
 /*   140 */    60,   38,  219,   58,   16,   68,   66,   65,   64,   34,
 /*   150 */    53,   12,   55,  189,   42,   14,  201,  202,   18,   63,
 /*   160 */    62,  186,  185,   43,  220,    2,    3,   33,  219,   58,
 /*   170 */    16,   68,   66,   65,   64,   34,   53,   12,   44,  157,
 /*   180 */    42,   14,   20,   70,   49,    4,   45,   74,    5,   11,
 /*   190 */   220,    6,   67,    7,  219,   58,   16,   68,   66,   65,
 /*   200 */    64,  298,   34,   53,   12,  160,  158,   42,   14,   54,
 /*   210 */   244,   56,   19,  162,   73,   10,   57,  220,   22,  175,
 /*   220 */    24,  219,   58,   16,   68,   66,   65,   64,   67,   17,
 /*   230 */    67,  194,  187,   72,   51,  197,   35,   37,   39,   41,
 /*   240 */   199,   69,   33,   21,   23,   25,  188,  177,  180,   28,
 /*   250 */    31,  179,   30,  247,    9,   11,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    72,    1,    2,    3,   72,    5,    6,    7,   58,   59,
 /*    10 */     8,    9,   56,   11,   12,   75,   16,   11,   12,   13,
 /*    20 */    20,   21,   22,   23,   24,   25,   26,   60,   61,   62,
 /*    30 */    63,   64,   65,   66,   67,   68,   69,   70,   71,   12,
 /*    40 */    13,   74,   11,   76,   13,    1,    2,    3,   73,    5,
 /*    50 */     6,    7,   11,   12,   75,    8,    9,   10,   11,   12,
 /*    60 */    16,   11,   12,   79,   20,   21,   22,   23,   24,   25,
 /*    70 */    26,    1,    2,    3,   27,    5,    6,    7,   31,   29,
 /*    80 */    12,    8,    9,   10,   11,   12,   16,   11,   12,   11,
 /*    90 */    20,   21,   22,   23,   24,   25,   26,    1,    2,    3,
 /*   100 */    27,    5,    6,    7,   31,    8,    9,   29,   11,   12,
 /*   110 */    11,   12,   16,   11,   12,   77,   20,   21,   22,   23,
 /*   120 */    24,   25,   26,    1,    2,    3,   11,    5,    6,    7,
 /*   130 */    28,   11,   12,   59,   11,   12,   11,   12,   16,   57,
 /*   140 */    12,   13,   20,   21,   22,   23,   24,   25,   26,    1,
 /*   150 */     2,    3,   29,    5,    6,    7,   11,   12,   11,   55,
 /*   160 */    13,   11,   12,   78,   16,   59,   59,   14,   20,   21,
 /*   170 */    22,   23,   24,   25,   26,    1,    2,    3,   78,    5,
 /*   180 */     6,    7,    4,   30,   54,   59,   78,   54,   59,   14,
 /*   190 */    16,   59,   14,   59,   20,   21,   22,   23,   24,   25,
 /*   200 */    26,    0,    1,    2,    3,   30,   30,    6,    7,   11,
 /*   210 */    11,   14,    4,   11,   12,   13,   11,   16,    4,   17,
 /*   220 */     4,   20,   21,   22,   23,   24,   25,   26,   14,   27,
 /*   230 */    14,    4,    4,   14,   14,   12,   15,   15,   14,   14,
 /*   240 */    11,   14,   14,   11,   11,   11,    4,   28,   28,   11,
 /*   250 */    13,   11,    4,   80,   15,   14,   80,   80,   80,   80,
 /*   260 */    80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
 /*   270 */    80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
 /*   280 */    80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
 /*   290 */    80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
 /*   300 */    80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
};
#define YY_SHIFT_COUNT    (75)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (248)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   256,    0,   44,   70,   96,  122,  148,  174,  201,   47,
 /*    10 */    73,  202,   50,  102,   27,   41,   68,  115,  256,  256,
 /*    20 */   256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
 /*    30 */   256,    2,   97,    6,  123,   76,   99,  120,  125,  128,
 /*    40 */   145,   31,  147,  178,  214,  216,  227,  153,  228,  175,
 /*    50 */   219,  150,  220,   78,  176,  198,  199,  197,  205,  221,
 /*    60 */   222,  224,  229,  225,  208,  232,  233,  237,  234,  223,
 /*    70 */   242,  238,  240,  239,  241,  248,
};
#define YY_REDUCE_COUNT (30)
#define YY_REDUCE_MIN   (-72)
#define YY_REDUCE_MAX   (134)
static const short yy_reduce_ofst[] = {
 /*     0 */   -50,  -33,  -33,  -33,  -33,  -33,  -33,  -33,  -33,  -72,
 /*    10 */   -68,  -44,  -60,  -25,  -16,  -21,   38,   82,  104,   74,
 /*    20 */   106,   85,  107,  100,  126,  108,  129,  132,  130,  133,
 /*    30 */   134,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   300,  245,  245,  245,  245,  245,  245,  245,  245,  245,
 /*    10 */   245,  245,  245,  245,  327,  245,  245,  245,  293,  300,
 /*    20 */   300,  318,  300,  318,  300,  318,  300,  300,  254,  254,
 /*    30 */   300,  245,  245,  245,  245,  245,  245,  245,  245,  245,
 /*    40 */   245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
 /*    50 */   245,  245,  245,  245,  245,  245,  245,  336,  245,  245,
 /*    60 */   245,  297,  245,  291,  245,  245,  245,  245,  245,  245,
 /*    70 */   245,  245,  245,  245,  252,  248,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "SOURCE",
  /*    2 */ "GEM",
  /*    3 */ "GROUP",
  /*    4 */ "DO",
  /*    5 */ "END",
  /*    6 */ "RUBY",
  /*    7 */ "GEMSPEC",
  /*    8 */ "LIT_TRUE",
  /*    9 */ "LIT_FALSE",
  /*   10 */ "LIT_NIL",
  /*   11 */ "STRING",
  /*   12 */ "SYMBOL",
  /*   13 */ "KEY",
  /*   14 */ "COMMA",
  /*   15 */ "HASHROCKET",
  /*   16 */ "NEWLINE",
  /*   17 */ "IDENT",
  /*   18 */ "UNSUPPORTED",
  /*   19 */ "ERROR",
  /*   20 */ "GIT_SOURCE",
  /*   21 */ "PLUGIN",
  /*   22 */ "PLATFORMS",
  /*   23 */ "PATH",
  /*   24 */ "GIT",
  /*   25 */ "GITHUB",
  /*   26 */ "INSTALL_IF",
  /*   27 */ "LBRACKET",
  /*   28 */ "RBRACKET",
  /*   29 */ "LPAREN",
  /*   30 */ "RPAREN",
  /*   31 */ "PERCENT_ARRAY",
  /*   32 */ "IF",
  /*   33 */ "UNLESS",
  /*   34 */ "ELSE",
  /*   35 */ "ELSIF",
  /*   36 */ "EVAL_GEMFILE",
  /*   37 */ "EQ",
  /*   38 */ "NEQ",
  /*   39 */ "GTE",
  /*   40 */ "LTE",
  /*   41 */ "GT",
  /*   42 */ "LT",
  /*   43 */ "MATCH",
  /*   44 */ "AND",
  /*   45 */ "OR",
  /*   46 */ "BANG",
  /*   47 */ "ASSIGN",
  /*   48 */ "DOT",
  /*   49 */ "COLON_COLON",
  /*   50 */ "PIPE",
  /*   51 */ "QUESTION",
  /*   52 */ "INTEGER",
  /*   53 */ "FLOAT_LIT",
  /*   54 */ "gem_opts",
  /*   55 */ "ruby_opts",
  /*   56 */ "string_array",
  /*   57 */ "string_array_items",
  /*   58 */ "file",
  /*   59 */ "stmts",
  /*   60 */ "stmt",
  /*   61 */ "source_stmt",
  /*   62 */ "gem_stmt",
  /*   63 */ "group_stmt",
  /*   64 */ "ruby_stmt",
  /*   65 */ "gemspec_stmt",
  /*   66 */ "platforms_stmt",
  /*   67 */ "plugin_stmt",
  /*   68 */ "path_stmt",
  /*   69 */ "git_stmt",
  /*   70 */ "github_stmt",
  /*   71 */ "install_if_stmt",
  /*   72 */ "typed_array",
  /*   73 */ "typed_array_items",
  /*   74 */ "group_open",
  /*   75 */ "name_list",
  /*   76 */ "platforms_open",
  /*   77 */ "platform_names",
  /*   78 */ "block_kw_opts",
  /*   79 */ "gemspec_opts",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "source_stmt ::= SOURCE STRING",
 /*   1 */ "source_stmt ::= SOURCE SYMBOL",
 /*   2 */ "source_stmt ::= SOURCE STRING DO stmts END",
 /*   3 */ "source_stmt ::= SOURCE LPAREN STRING RPAREN",
 /*   4 */ "gem_stmt ::= GEM STRING gem_opts",
 /*   5 */ "gem_stmt ::= GEM LPAREN STRING gem_opts RPAREN",
 /*   6 */ "gem_opts ::=",
 /*   7 */ "gem_opts ::= gem_opts COMMA STRING",
 /*   8 */ "gem_opts ::= gem_opts COMMA KEY LIT_FALSE",
 /*   9 */ "gem_opts ::= gem_opts COMMA KEY LIT_TRUE",
 /*  10 */ "gem_opts ::= gem_opts COMMA KEY LIT_NIL",
 /*  11 */ "gem_opts ::= gem_opts COMMA KEY SYMBOL",
 /*  12 */ "gem_opts ::= gem_opts COMMA KEY STRING",
 /*  13 */ "gem_opts ::= gem_opts COMMA KEY typed_array",
 /*  14 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE",
 /*  15 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE",
 /*  16 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL",
 /*  17 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL",
 /*  18 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING",
 /*  19 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET typed_array",
 /*  20 */ "gem_opts ::= gem_opts COMMA IDENT",
 /*  21 */ "gem_opts ::= gem_opts COMMA string_array",
 /*  22 */ "string_array ::= LBRACKET string_array_items RBRACKET",
 /*  23 */ "string_array_items ::= STRING",
 /*  24 */ "string_array_items ::= string_array_items COMMA STRING",
 /*  25 */ "typed_array ::= LBRACKET typed_array_items RBRACKET",
 /*  26 */ "typed_array ::= LBRACKET RBRACKET",
 /*  27 */ "typed_array ::= PERCENT_ARRAY",
 /*  28 */ "typed_array_items ::= SYMBOL",
 /*  29 */ "typed_array_items ::= STRING",
 /*  30 */ "typed_array_items ::= typed_array_items COMMA SYMBOL",
 /*  31 */ "typed_array_items ::= typed_array_items COMMA STRING",
 /*  32 */ "group_open ::= GROUP name_list DO",
 /*  33 */ "group_open ::= GROUP LPAREN name_list RPAREN DO",
 /*  34 */ "group_stmt ::= group_open stmts END",
 /*  35 */ "name_list ::= SYMBOL",
 /*  36 */ "name_list ::= STRING",
 /*  37 */ "name_list ::= name_list COMMA SYMBOL",
 /*  38 */ "name_list ::= name_list COMMA STRING",
 /*  39 */ "platforms_open ::= PLATFORMS platform_names DO",
 /*  40 */ "platforms_stmt ::= platforms_open stmts END",
 /*  41 */ "platform_names ::= SYMBOL",
 /*  42 */ "platform_names ::= platform_names COMMA SYMBOL",
 /*  43 */ "ruby_stmt ::= RUBY STRING ruby_opts",
 /*  44 */ "ruby_stmt ::= RUBY KEY STRING",
 /*  45 */ "ruby_opts ::=",
 /*  46 */ "ruby_opts ::= ruby_opts COMMA KEY STRING",
 /*  47 */ "ruby_opts ::= ruby_opts COMMA KEY SYMBOL",
 /*  48 */ "ruby_opts ::= ruby_opts COMMA STRING",
 /*  49 */ "gemspec_stmt ::= GEMSPEC gemspec_opts",
 /*  50 */ "file ::= stmts",
 /*  51 */ "stmts ::= stmts stmt",
 /*  52 */ "stmts ::=",
 /*  53 */ "stmt ::= source_stmt",
 /*  54 */ "stmt ::= gem_stmt",
 /*  55 */ "stmt ::= group_stmt",
 /*  56 */ "stmt ::= ruby_stmt",
 /*  57 */ "stmt ::= gemspec_stmt",
 /*  58 */ "stmt ::= platforms_stmt",
 /*  59 */ "stmt ::= plugin_stmt",
 /*  60 */ "stmt ::= path_stmt",
 /*  61 */ "stmt ::= git_stmt",
 /*  62 */ "stmt ::= github_stmt",
 /*  63 */ "stmt ::= install_if_stmt",
 /*  64 */ "stmt ::= GIT_SOURCE",
 /*  65 */ "stmt ::= NEWLINE",
 /*  66 */ "name_list ::= name_list COMMA KEY LIT_TRUE",
 /*  67 */ "name_list ::= name_list COMMA KEY LIT_FALSE",
 /*  68 */ "name_list ::= name_list COMMA KEY STRING",
 /*  69 */ "name_list ::= name_list COMMA KEY SYMBOL",
 /*  70 */ "block_kw_opts ::=",
 /*  71 */ "block_kw_opts ::= block_kw_opts COMMA KEY STRING",
 /*  72 */ "block_kw_opts ::= block_kw_opts COMMA KEY SYMBOL",
 /*  73 */ "block_kw_opts ::= block_kw_opts COMMA KEY LIT_TRUE",
 /*  74 */ "block_kw_opts ::= block_kw_opts COMMA KEY LIT_FALSE",
 /*  75 */ "path_stmt ::= PATH STRING block_kw_opts DO stmts END",
 /*  76 */ "git_stmt ::= GIT STRING block_kw_opts DO stmts END",
 /*  77 */ "github_stmt ::= GITHUB STRING block_kw_opts DO stmts END",
 /*  78 */ "install_if_stmt ::= INSTALL_IF DO stmts END",
 /*  79 */ "gemspec_opts ::=",
 /*  80 */ "gemspec_opts ::= gemspec_opts COMMA KEY STRING",
 /*  81 */ "gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL",
 /*  82 */ "gemspec_opts ::= KEY STRING",
 /*  83 */ "gemspec_opts ::= KEY SYMBOL",
 /*  84 */ "gemspec_opts ::= SYMBOL HASHROCKET STRING",
 /*  85 */ "gemspec_opts ::= SYMBOL HASHROCKET SYMBOL",
 /*  86 */ "gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING",
 /*  87 */ "gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL",
 /*  88 */ "plugin_stmt ::= PLUGIN STRING",
 /*  89 */ "plugin_stmt ::= PLUGIN STRING COMMA STRING",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* Default NON-TERMINAL Destructor */
    case 58: /* file */
    case 59: /* stmts */
    case 60: /* stmt */
    case 61: /* source_stmt */
    case 62: /* gem_stmt */
    case 63: /* group_stmt */
    case 64: /* ruby_stmt */
    case 65: /* gemspec_stmt */
    case 66: /* platforms_stmt */
    case 67: /* plugin_stmt */
    case 68: /* path_stmt */
    case 69: /* git_stmt */
    case 70: /* github_stmt */
    case 71: /* install_if_stmt */
    case 74: /* group_open */
    case 75: /* name_list */
    case 76: /* platforms_open */
    case 77: /* platform_names */
    case 78: /* block_kw_opts */
    case 79: /* gemspec_opts */
{
#line 130 "src/gemfile/parser.y"
 (void)(yypminor->yy0); (void)gf; 
#line 885 "src/gemfile/parser.c"
}
      break;
    case 54: /* gem_opts */
    case 55: /* ruby_opts */
    case 56: /* string_array */
    case 57: /* string_array_items */
    case 72: /* typed_array */
    case 73: /* typed_array_items */
{
#line 142 "src/gemfile/parser.y"
 gem_opts_acc_free(&(yypminor->yy50)); 
#line 897 "src/gemfile/parser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    61,  /* (0) source_stmt ::= SOURCE STRING */
    61,  /* (1) source_stmt ::= SOURCE SYMBOL */
    61,  /* (2) source_stmt ::= SOURCE STRING DO stmts END */
    61,  /* (3) source_stmt ::= SOURCE LPAREN STRING RPAREN */
    62,  /* (4) gem_stmt ::= GEM STRING gem_opts */
    62,  /* (5) gem_stmt ::= GEM LPAREN STRING gem_opts RPAREN */
    54,  /* (6) gem_opts ::= */
    54,  /* (7) gem_opts ::= gem_opts COMMA STRING */
    54,  /* (8) gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
    54,  /* (9) gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
    54,  /* (10) gem_opts ::= gem_opts COMMA KEY LIT_NIL */
    54,  /* (11) gem_opts ::= gem_opts COMMA KEY SYMBOL */
    54,  /* (12) gem_opts ::= gem_opts COMMA KEY STRING */
    54,  /* (13) gem_opts ::= gem_opts COMMA KEY typed_array */
    54,  /* (14) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
    54,  /* (15) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
    54,  /* (16) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
    54,  /* (17) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
    54,  /* (18) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
    54,  /* (19) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET typed_array */
    54,  /* (20) gem_opts ::= gem_opts COMMA IDENT */
    54,  /* (21) gem_opts ::= gem_opts COMMA string_array */
    56,  /* (22) string_array ::= LBRACKET string_array_items RBRACKET */
    57,  /* (23) string_array_items ::= STRING */
    57,  /* (24) string_array_items ::= string_array_items COMMA STRING */
    72,  /* (25) typed_array ::= LBRACKET typed_array_items RBRACKET */
    72,  /* (26) typed_array ::= LBRACKET RBRACKET */
    72,  /* (27) typed_array ::= PERCENT_ARRAY */
    73,  /* (28) typed_array_items ::= SYMBOL */
    73,  /* (29) typed_array_items ::= STRING */
    73,  /* (30) typed_array_items ::= typed_array_items COMMA SYMBOL */
    73,  /* (31) typed_array_items ::= typed_array_items COMMA STRING */
    74,  /* (32) group_open ::= GROUP name_list DO */
    74,  /* (33) group_open ::= GROUP LPAREN name_list RPAREN DO */
    63,  /* (34) group_stmt ::= group_open stmts END */
    75,  /* (35) name_list ::= SYMBOL */
    75,  /* (36) name_list ::= STRING */
    75,  /* (37) name_list ::= name_list COMMA SYMBOL */
    75,  /* (38) name_list ::= name_list COMMA STRING */
    76,  /* (39) platforms_open ::= PLATFORMS platform_names DO */
    66,  /* (40) platforms_stmt ::= platforms_open stmts END */
    77,  /* (41) platform_names ::= SYMBOL */
    77,  /* (42) platform_names ::= platform_names COMMA SYMBOL */
    64,  /* (43) ruby_stmt ::= RUBY STRING ruby_opts */
    64,  /* (44) ruby_stmt ::= RUBY KEY STRING */
    55,  /* (45) ruby_opts ::= */
    55,  /* (46) ruby_opts ::= ruby_opts COMMA KEY STRING */
    55,  /* (47) ruby_opts ::= ruby_opts COMMA KEY SYMBOL */
    55,  /* (48) ruby_opts ::= ruby_opts COMMA STRING */
    65,  /* (49) gemspec_stmt ::= GEMSPEC gemspec_opts */
    58,  /* (50) file ::= stmts */
    59,  /* (51) stmts ::= stmts stmt */
    59,  /* (52) stmts ::= */
    60,  /* (53) stmt ::= source_stmt */
    60,  /* (54) stmt ::= gem_stmt */
    60,  /* (55) stmt ::= group_stmt */
    60,  /* (56) stmt ::= ruby_stmt */
    60,  /* (57) stmt ::= gemspec_stmt */
    60,  /* (58) stmt ::= platforms_stmt */
    60,  /* (59) stmt ::= plugin_stmt */
    60,  /* (60) stmt ::= path_stmt */
    60,  /* (61) stmt ::= git_stmt */
    60,  /* (62) stmt ::= github_stmt */
    60,  /* (63) stmt ::= install_if_stmt */
    60,  /* (64) stmt ::= GIT_SOURCE */
    60,  /* (65) stmt ::= NEWLINE */
    75,  /* (66) name_list ::= name_list COMMA KEY LIT_TRUE */
    75,  /* (67) name_list ::= name_list COMMA KEY LIT_FALSE */
    75,  /* (68) name_list ::= name_list COMMA KEY STRING */
    75,  /* (69) name_list ::= name_list COMMA KEY SYMBOL */
    78,  /* (70) block_kw_opts ::= */
    78,  /* (71) block_kw_opts ::= block_kw_opts COMMA KEY STRING */
    78,  /* (72) block_kw_opts ::= block_kw_opts COMMA KEY SYMBOL */
    78,  /* (73) block_kw_opts ::= block_kw_opts COMMA KEY LIT_TRUE */
    78,  /* (74) block_kw_opts ::= block_kw_opts COMMA KEY LIT_FALSE */
    68,  /* (75) path_stmt ::= PATH STRING block_kw_opts DO stmts END */
    69,  /* (76) git_stmt ::= GIT STRING block_kw_opts DO stmts END */
    70,  /* (77) github_stmt ::= GITHUB STRING block_kw_opts DO stmts END */
    71,  /* (78) install_if_stmt ::= INSTALL_IF DO stmts END */
    79,  /* (79) gemspec_opts ::= */
    79,  /* (80) gemspec_opts ::= gemspec_opts COMMA KEY STRING */
    79,  /* (81) gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */
    79,  /* (82) gemspec_opts ::= KEY STRING */
    79,  /* (83) gemspec_opts ::= KEY SYMBOL */
    79,  /* (84) gemspec_opts ::= SYMBOL HASHROCKET STRING */
    79,  /* (85) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */
    79,  /* (86) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
    79,  /* (87) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */
    67,  /* (88) plugin_stmt ::= PLUGIN STRING */
    67,  /* (89) plugin_stmt ::= PLUGIN STRING COMMA STRING */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -2,  /* (0) source_stmt ::= SOURCE STRING */
   -2,  /* (1) source_stmt ::= SOURCE SYMBOL */
   -5,  /* (2) source_stmt ::= SOURCE STRING DO stmts END */
   -4,  /* (3) source_stmt ::= SOURCE LPAREN STRING RPAREN */
   -3,  /* (4) gem_stmt ::= GEM STRING gem_opts */
   -5,  /* (5) gem_stmt ::= GEM LPAREN STRING gem_opts RPAREN */
    0,  /* (6) gem_opts ::= */
   -3,  /* (7) gem_opts ::= gem_opts COMMA STRING */
   -4,  /* (8) gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
   -4,  /* (9) gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
   -4,  /* (10) gem_opts ::= gem_opts COMMA KEY LIT_NIL */
   -4,  /* (11) gem_opts ::= gem_opts COMMA KEY SYMBOL */
   -4,  /* (12) gem_opts ::= gem_opts COMMA KEY STRING */
   -4,  /* (13) gem_opts ::= gem_opts COMMA KEY typed_array */
   -5,  /* (14) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
   -5,  /* (15) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
   -5,  /* (16) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
   -5,  /* (17) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
   -5,  /* (18) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
   -5,  /* (19) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET typed_array */
   -3,  /* (20) gem_opts ::= gem_opts COMMA IDENT */
   -3,  /* (21) gem_opts ::= gem_opts COMMA string_array */
   -3,  /* (22) string_array ::= LBRACKET string_array_items RBRACKET */
   -1,  /* (23) string_array_items ::= STRING */
   -3,  /* (24) string_array_items ::= string_array_items COMMA STRING */
   -3,  /* (25) typed_array ::= LBRACKET typed_array_items RBRACKET */
   -2,  /* (26) typed_array ::= LBRACKET RBRACKET */
   -1,  /* (27) typed_array ::= PERCENT_ARRAY */
   -1,  /* (28) typed_array_items ::= SYMBOL */
   -1,  /* (29) typed_array_items ::= STRING */
   -3,  /* (30) typed_array_items ::= typed_array_items COMMA SYMBOL */
   -3,  /* (31) typed_array_items ::= typed_array_items COMMA STRING */
   -3,  /* (32) group_open ::= GROUP name_list DO */
   -5,  /* (33) group_open ::= GROUP LPAREN name_list RPAREN DO */
   -3,  /* (34) group_stmt ::= group_open stmts END */
   -1,  /* (35) name_list ::= SYMBOL */
   -1,  /* (36) name_list ::= STRING */
   -3,  /* (37) name_list ::= name_list COMMA SYMBOL */
   -3,  /* (38) name_list ::= name_list COMMA STRING */
   -3,  /* (39) platforms_open ::= PLATFORMS platform_names DO */
   -3,  /* (40) platforms_stmt ::= platforms_open stmts END */
   -1,  /* (41) platform_names ::= SYMBOL */
   -3,  /* (42) platform_names ::= platform_names COMMA SYMBOL */
   -3,  /* (43) ruby_stmt ::= RUBY STRING ruby_opts */
   -3,  /* (44) ruby_stmt ::= RUBY KEY STRING */
    0,  /* (45) ruby_opts ::= */
   -4,  /* (46) ruby_opts ::= ruby_opts COMMA KEY STRING */
   -4,  /* (47) ruby_opts ::= ruby_opts COMMA KEY SYMBOL */
   -3,  /* (48) ruby_opts ::= ruby_opts COMMA STRING */
   -2,  /* (49) gemspec_stmt ::= GEMSPEC gemspec_opts */
   -1,  /* (50) file ::= stmts */
   -2,  /* (51) stmts ::= stmts stmt */
    0,  /* (52) stmts ::= */
   -1,  /* (53) stmt ::= source_stmt */
   -1,  /* (54) stmt ::= gem_stmt */
   -1,  /* (55) stmt ::= group_stmt */
   -1,  /* (56) stmt ::= ruby_stmt */
   -1,  /* (57) stmt ::= gemspec_stmt */
   -1,  /* (58) stmt ::= platforms_stmt */
   -1,  /* (59) stmt ::= plugin_stmt */
   -1,  /* (60) stmt ::= path_stmt */
   -1,  /* (61) stmt ::= git_stmt */
   -1,  /* (62) stmt ::= github_stmt */
   -1,  /* (63) stmt ::= install_if_stmt */
   -1,  /* (64) stmt ::= GIT_SOURCE */
   -1,  /* (65) stmt ::= NEWLINE */
   -4,  /* (66) name_list ::= name_list COMMA KEY LIT_TRUE */
   -4,  /* (67) name_list ::= name_list COMMA KEY LIT_FALSE */
   -4,  /* (68) name_list ::= name_list COMMA KEY STRING */
   -4,  /* (69) name_list ::= name_list COMMA KEY SYMBOL */
    0,  /* (70) block_kw_opts ::= */
   -4,  /* (71) block_kw_opts ::= block_kw_opts COMMA KEY STRING */
   -4,  /* (72) block_kw_opts ::= block_kw_opts COMMA KEY SYMBOL */
   -4,  /* (73) block_kw_opts ::= block_kw_opts COMMA KEY LIT_TRUE */
   -4,  /* (74) block_kw_opts ::= block_kw_opts COMMA KEY LIT_FALSE */
   -6,  /* (75) path_stmt ::= PATH STRING block_kw_opts DO stmts END */
   -6,  /* (76) git_stmt ::= GIT STRING block_kw_opts DO stmts END */
   -6,  /* (77) github_stmt ::= GITHUB STRING block_kw_opts DO stmts END */
   -4,  /* (78) install_if_stmt ::= INSTALL_IF DO stmts END */
    0,  /* (79) gemspec_opts ::= */
   -4,  /* (80) gemspec_opts ::= gemspec_opts COMMA KEY STRING */
   -4,  /* (81) gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */
   -2,  /* (82) gemspec_opts ::= KEY STRING */
   -2,  /* (83) gemspec_opts ::= KEY SYMBOL */
   -3,  /* (84) gemspec_opts ::= SYMBOL HASHROCKET STRING */
   -3,  /* (85) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */
   -5,  /* (86) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
   -5,  /* (87) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */
   -2,  /* (88) plugin_stmt ::= PLUGIN STRING */
   -4,  /* (89) plugin_stmt ::= PLUGIN STRING COMMA STRING */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* source_stmt ::= SOURCE STRING */
#line 207 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[0].minor.yy0, 1, 1);
}
#line 1418 "src/gemfile/parser.c"
        break;
      case 1: /* source_stmt ::= SOURCE SYMBOL */
#line 213 "src/gemfile/parser.y"
{
    free(gf->source);
    char *sym = tok_strdup(yymsp[0].minor.yy0, 1, 0);  /* strip leading colon */
    if (strcmp(sym, "rubygems") == 0 || strcmp(sym, "gemcutter") == 0) {
        gf->source = strdup("https://rubygems.org");
        free(sym);
    } else {
        gf->source = sym;  /* unknown symbol -- store as-is */
    }
}
#line 1432 "src/gemfile/parser.c"
        break;
      case 2: /* source_stmt ::= SOURCE STRING DO stmts END */
#line 227 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[-3].minor.yy0, 1, 1);
}
#line 1440 "src/gemfile/parser.c"
  yy_destructor(yypParser,59,&yymsp[-1].minor);
        break;
      case 3: /* source_stmt ::= SOURCE LPAREN STRING RPAREN */
#line 233 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
}
#line 1449 "src/gemfile/parser.c"
        break;
      case 4: /* gem_stmt ::= GEM STRING gem_opts */
#line 242 "src/gemfile/parser.y"
{
    struct wow_gemfile_dep dep;
    memset(&dep, 0, sizeof(dep));
    dep.name          = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
    dep.constraints   = yymsp[0].minor.yy50.constraints;
    dep.n_constraints = yymsp[0].minor.yy50.n_constraints;
    dep.autorequire   = yymsp[0].minor.yy50.autorequire;
    dep.n_autorequire = yymsp[0].minor.yy50.n_autorequire;
    dep.autorequire_specified = yymsp[0].minor.yy50.autorequire_specified;
    dep.platforms     = yymsp[0].minor.yy50.platforms;
    dep.n_platforms   = yymsp[0].minor.yy50.n_platforms;

    /* groups: keyword option takes priority over block context */
    if (yymsp[0].minor.yy50.n_groups > 0) {
        dep.groups = yymsp[0].minor.yy50.groups;
        dep.n_groups = yymsp[0].minor.yy50.n_groups;
    } else if (gf->_n_current_groups > 0) {
        dep.groups = malloc(sizeof(char *) * (size_t)gf->_n_current_groups);
        for (int i = 0; i < gf->_n_current_groups; i++)
            dep.groups[i] = strdup(gf->_current_groups[i]);
        dep.n_groups = gf->_n_current_groups;
    } else {
        dep.groups = malloc(sizeof(char *));
        dep.groups[0] = strdup("default");
        dep.n_groups = 1;
    }

    /* platforms from block context */
    if (gf->_n_current_platforms > 0 && dep.n_platforms == 0) {
        dep.platforms = malloc(sizeof(char *) * (size_t)gf->_n_current_platforms);
        for (int i = 0; i < gf->_n_current_platforms; i++)
            dep.platforms[i] = strdup(gf->_current_platforms[i]);
        dep.n_platforms = gf->_n_current_platforms;
    }

    /* Prevent gem_opts destructor from freeing transferred pointers */
    yymsp[0].minor.yy50.constraints = NULL;
    yymsp[0].minor.yy50.n_constraints = 0;
    yymsp[0].minor.yy50.groups = NULL;
    yymsp[0].minor.yy50.n_groups = 0;
    yymsp[0].minor.yy50.autorequire = NULL;
    yymsp[0].minor.yy50.n_autorequire = 0;
    yymsp[0].minor.yy50.platforms = NULL;
    yymsp[0].minor.yy50.n_platforms = 0;

    wow_gemfile_add_dep(gf, &dep);
}
#line 1500 "src/gemfile/parser.c"
        break;
      case 5: /* gem_stmt ::= GEM LPAREN STRING gem_opts RPAREN */
#line 291 "src/gemfile/parser.y"
{
    struct wow_gemfile_dep dep;
    memset(&dep, 0, sizeof(dep));
    dep.name          = tok_strdup(yymsp[-2].minor.yy0, 1, 1);
    dep.constraints   = yymsp[-1].minor.yy50.constraints;
    dep.n_constraints = yymsp[-1].minor.yy50.n_constraints;
    dep.autorequire   = yymsp[-1].minor.yy50.autorequire;
    dep.n_autorequire = yymsp[-1].minor.yy50.n_autorequire;
    dep.autorequire_specified = yymsp[-1].minor.yy50.autorequire_specified;
    dep.platforms     = yymsp[-1].minor.yy50.platforms;
    dep.n_platforms   = yymsp[-1].minor.yy50.n_platforms;

    if (yymsp[-1].minor.yy50.n_groups > 0) {
        dep.groups = yymsp[-1].minor.yy50.groups;
        dep.n_groups = yymsp[-1].minor.yy50.n_groups;
    } else if (gf->_n_current_groups > 0) {
        dep.groups = malloc(sizeof(char *) * (size_t)gf->_n_current_groups);
        for (int i = 0; i < gf->_n_current_groups; i++)
            dep.groups[i] = strdup(gf->_current_groups[i]);
        dep.n_groups = gf->_n_current_groups;
    } else {
        dep.groups = malloc(sizeof(char *));
        dep.groups[0] = strdup("default");
        dep.n_groups = 1;
    }

    if (gf->_n_current_platforms > 0 && dep.n_platforms == 0) {
        dep.platforms = malloc(sizeof(char *) * (size_t)gf->_n_current_platforms);
        for (int i = 0; i < gf->_n_current_platforms; i++)
            dep.platforms[i] = strdup(gf->_current_platforms[i]);
        dep.n_platforms = gf->_n_current_platforms;
    }

    yymsp[-1].minor.yy50.constraints = NULL;
    yymsp[-1].minor.yy50.n_constraints = 0;
    yymsp[-1].minor.yy50.groups = NULL;
    yymsp[-1].minor.yy50.n_groups = 0;
    yymsp[-1].minor.yy50.autorequire = NULL;
    yymsp[-1].minor.yy50.n_autorequire = 0;
    yymsp[-1].minor.yy50.platforms = NULL;
    yymsp[-1].minor.yy50.n_platforms = 0;

    wow_gemfile_add_dep(gf, &dep);
}
#line 1548 "src/gemfile/parser.c"
        break;
      case 6: /* gem_opts ::= */
      case 45: /* ruby_opts ::= */ yytestcase(yyruleno==45);
#line 337 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yymsp[1].minor.yy50);
}
#line 1556 "src/gemfile/parser.c"
        break;
      case 7: /* gem_opts ::= gem_opts COMMA STRING */
#line 341 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));  /* prevent double-free */
    gem_opts_acc_add_constraint(&yylhsminor.yy50, tok_strdup(yymsp[0].minor.yy0, 1, 1));
}
#line 1565 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 8: /* gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
#line 347 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);  /* strip trailing colon */
    if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = true;
        /* require: false → empty autorequire array */
        yylhsminor.yy50.autorequire = NULL;
        yylhsminor.yy50.n_autorequire = 0;
    }
    free(key);
}
#line 1582 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 9: /* gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
#line 360 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);
    if (strcmp(key, "require") == 0) {
        /* require: true → not specified (use default) */
        yylhsminor.yy50.autorequire_specified = false;
    }
    free(key);
}
#line 1597 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 10: /* gem_opts ::= gem_opts COMMA KEY LIT_NIL */
#line 371 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);
    if (strcmp(key, "require") == 0) {
        /* require: nil == require: false */
        yylhsminor.yy50.autorequire_specified = true;
        yylhsminor.yy50.autorequire = NULL;
        yylhsminor.yy50.n_autorequire = 0;
    }
    free(key);
}
#line 1614 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 11: /* gem_opts ::= gem_opts COMMA KEY SYMBOL */
#line 384 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);  /* strip trailing colon */
    if (strcmp(key, "group") == 0 || strcmp(key, "groups") == 0) {
        gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                                tok_strdup(yymsp[0].minor.yy0, 1, 0));
    } else if (strcmp(key, "platform") == 0 || strcmp(key, "platforms") == 0) {
        gem_opts_acc_add_string(&yylhsminor.yy50.platforms, &yylhsminor.yy50.n_platforms, &yylhsminor.yy50.platforms_cap,
                                tok_strdup(yymsp[0].minor.yy0, 1, 0));
    }
    free(key);
}
#line 1632 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 12: /* gem_opts ::= gem_opts COMMA KEY STRING */
#line 398 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);
    if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = true;
        gem_opts_acc_add_string(&yylhsminor.yy50.autorequire, &yylhsminor.yy50.n_autorequire, &yylhsminor.yy50.autorequire_cap,
                                tok_strdup(yymsp[0].minor.yy0, 1, 1));
    }
    free(key);
}
#line 1648 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 13: /* gem_opts ::= gem_opts COMMA KEY typed_array */
#line 410 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);
    if (strcmp(key, "groups") == 0 || strcmp(key, "group") == 0) {
        /* Transfer groups from array */
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)
            gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
        yymsp[0].minor.yy50.n_groups = 0;
    } else if (strcmp(key, "platforms") == 0 || strcmp(key, "platform") == 0) {
        /* Transfer platforms from array */
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)  /* yymsp[0].minor.yy50.groups holds platforms here */
            gem_opts_acc_add_string(&yylhsminor.yy50.platforms, &yylhsminor.yy50.n_platforms, &yylhsminor.yy50.platforms_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
    } else if (strcmp(key, "require") == 0) {
        /* Transfer autorequire paths from array */
        yylhsminor.yy50.autorequire_specified = true;
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)
            gem_opts_acc_add_string(&yylhsminor.yy50.autorequire, &yylhsminor.yy50.n_autorequire, &yylhsminor.yy50.autorequire_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
    }
    free(key);
}
#line 1680 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 14: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
#line 439 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);  /* strip leading colon */
    if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = true;
        yylhsminor.yy50.autorequire = NULL;
        yylhsminor.yy50.n_autorequire = 0;
    }
    free(key);
}
#line 1696 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 15: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
#line 451 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);
    if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = false;  /* require: true is default */
    }
    free(key);
}
#line 1710 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 16: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
#line 461 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);
    if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = true;
        yylhsminor.yy50.autorequire = NULL;
        yylhsminor.yy50.n_autorequire = 0;
    }
    free(key);
}
#line 1726 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 17: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
#line 473 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);
    if (strcmp(key, "group") == 0 || strcmp(key, "groups") == 0) {
        gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                                tok_strdup(yymsp[0].minor.yy0, 1, 0));
    } else if (strcmp(key, "platform") == 0 || strcmp(key, "platforms") == 0) {
        gem_opts_acc_add_string(&yylhsminor.yy50.platforms, &yylhsminor.yy50.n_platforms, &yylhsminor.yy50.platforms_cap,
                                tok_strdup(yymsp[0].minor.yy0, 1, 0));
    }
    free(key);
}
#line 1744 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 18: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
#line 487 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    /* Unknown hashrocket key with string value -- ignore */
}
#line 1754 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 19: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET typed_array */
#line 493 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-4].minor.yy50;
    memset(&yymsp[-4].minor.yy50, 0, sizeof(yymsp[-4].minor.yy50));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);  /* strip leading colon */
    if (strcmp(key, "groups") == 0 || strcmp(key, "group") == 0) {
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)
            gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
    } else if (strcmp(key, "platforms") == 0 || strcmp(key, "platform") == 0) {
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)
            gem_opts_acc_add_string(&yylhsminor.yy50.platforms, &yylhsminor.yy50.n_platforms, &yylhsminor.yy50.platforms_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
    } else if (strcmp(key, "require") == 0) {
        yylhsminor.yy50.autorequire_specified = true;
        for (int i = 0; i < yymsp[0].minor.yy50.n_groups; i++)
            gem_opts_acc_add_string(&yylhsminor.yy50.autorequire, &yylhsminor.yy50.n_autorequire, &yylhsminor.yy50.autorequire_cap, yymsp[0].minor.yy50.groups[i]);
        free(yymsp[0].minor.yy50.groups);
        yymsp[0].minor.yy50.groups = NULL;
    }
    free(key);
}
#line 1782 "src/gemfile/parser.c"
  yymsp[-4].minor.yy50 = yylhsminor.yy50;
        break;
      case 20: /* gem_opts ::= gem_opts COMMA IDENT */
#line 518 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    /* Accept but ignore — variable couldn't be resolved by evaluator */
}
#line 1792 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 21: /* gem_opts ::= gem_opts COMMA string_array */
#line 525 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    for (int i = 0; i < yymsp[0].minor.yy50.n_constraints; i++)
        gem_opts_acc_add_constraint(&yylhsminor.yy50, yymsp[0].minor.yy50.constraints[i]);
    free(yymsp[0].minor.yy50.constraints);  /* strings transferred, free container only */
    yymsp[0].minor.yy50.constraints = NULL;
    yymsp[0].minor.yy50.n_constraints = 0;
}
#line 1806 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 22: /* string_array ::= LBRACKET string_array_items RBRACKET */
      case 25: /* typed_array ::= LBRACKET typed_array_items RBRACKET */ yytestcase(yyruleno==25);
#line 539 "src/gemfile/parser.y"
{
    yymsp[-2].minor.yy50 = yymsp[-1].minor.yy50;
    memset(&yymsp[-1].minor.yy50, 0, sizeof(yymsp[-1].minor.yy50));
}
#line 1816 "src/gemfile/parser.c"
        break;
      case 23: /* string_array_items ::= STRING */
#line 544 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yylhsminor.yy50);
    gem_opts_acc_add_constraint(&yylhsminor.yy50, tok_strdup(yymsp[0].minor.yy0, 1, 1));
}
#line 1824 "src/gemfile/parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 24: /* string_array_items ::= string_array_items COMMA STRING */
#line 549 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    gem_opts_acc_add_constraint(&yylhsminor.yy50, tok_strdup(yymsp[0].minor.yy0, 1, 1));
}
#line 1834 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 26: /* typed_array ::= LBRACKET RBRACKET */
#line 570 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yymsp[-1].minor.yy50);
}
#line 1842 "src/gemfile/parser.c"
        break;
      case 27: /* typed_array ::= PERCENT_ARRAY */
#line 574 "src/gemfile/parser.y"
{
    parse_percent_array(&yylhsminor.yy50, yymsp[0].minor.yy0);
}
#line 1849 "src/gemfile/parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 28: /* typed_array_items ::= SYMBOL */
#line 578 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yylhsminor.yy50);
    gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                            tok_strdup(yymsp[0].minor.yy0, 1, 0));  /* strip leading colon */
}
#line 1859 "src/gemfile/parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 29: /* typed_array_items ::= STRING */
#line 584 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yylhsminor.yy50);
    gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                            tok_strdup(yymsp[0].minor.yy0, 1, 1));  /* strip quotes */
}
#line 1869 "src/gemfile/parser.c"
  yymsp[0].minor.yy50 = yylhsminor.yy50;
        break;
      case 30: /* typed_array_items ::= typed_array_items COMMA SYMBOL */
#line 590 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                            tok_strdup(yymsp[0].minor.yy0, 1, 0));
}
#line 1880 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 31: /* typed_array_items ::= typed_array_items COMMA STRING */
#line 597 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    gem_opts_acc_add_string(&yylhsminor.yy50.groups, &yylhsminor.yy50.n_groups, &yylhsminor.yy50.groups_cap,
                            tok_strdup(yymsp[0].minor.yy0, 1, 1));
}
#line 1891 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 32: /* group_open ::= GROUP name_list DO */
#line 610 "src/gemfile/parser.y"
{
    /* _current_groups was set by name_list reduction */
}
#line 1899 "src/gemfile/parser.c"
  yy_destructor(yypParser,75,&yymsp[-1].minor);
        break;
      case 33: /* group_open ::= GROUP LPAREN name_list RPAREN DO */
#line 614 "src/gemfile/parser.y"
{
    /* _current_groups was set by name_list reduction */
}
#line 1907 "src/gemfile/parser.c"
  yy_destructor(yypParser,75,&yymsp[-2].minor);
        break;
      case 34: /* group_stmt ::= group_open stmts END */
{  yy_destructor(yypParser,74,&yymsp[-2].minor);
#line 618 "src/gemfile/parser.y"
{
    for (int i = 0; i < gf->_n_current_groups; i++)
        free(gf->_current_groups[i]);
    free(gf->_current_groups);
    gf->_current_groups = NULL;
    gf->_n_current_groups = 0;
}
#line 1920 "src/gemfile/parser.c"
  yy_destructor(yypParser,59,&yymsp[-1].minor);
}
        break;
      case 35: /* name_list ::= SYMBOL */
#line 626 "src/gemfile/parser.y"
{
    for (int i = 0; i < gf->_n_current_groups; i++)
        free(gf->_current_groups[i]);
    free(gf->_current_groups);
    gf->_current_groups = malloc(sizeof(char *));
    gf->_current_groups[0] = tok_strdup(yymsp[0].minor.yy0, 1, 0);
    gf->_n_current_groups = 1;
}
#line 1934 "src/gemfile/parser.c"
        break;
      case 36: /* name_list ::= STRING */
#line 635 "src/gemfile/parser.y"
{
    for (int i = 0; i < gf->_n_current_groups; i++)
        free(gf->_current_groups[i]);
    free(gf->_current_groups);
    gf->_current_groups = malloc(sizeof(char *));
    gf->_current_groups[0] = tok_strdup(yymsp[0].minor.yy0, 1, 1);
    gf->_n_current_groups = 1;
}
#line 1946 "src/gemfile/parser.c"
        break;
      case 37: /* name_list ::= name_list COMMA SYMBOL */
{  yy_destructor(yypParser,75,&yymsp[-2].minor);
#line 644 "src/gemfile/parser.y"
{
    gf->_current_groups = realloc(gf->_current_groups,
        sizeof(char *) * (size_t)(gf->_n_current_groups + 1));
    gf->_current_groups[gf->_n_current_groups] = tok_strdup(yymsp[0].minor.yy0, 1, 0);
    gf->_n_current_groups++;
}
#line 1957 "src/gemfile/parser.c"
}
        break;
      case 38: /* name_list ::= name_list COMMA STRING */
{  yy_destructor(yypParser,75,&yymsp[-2].minor);
#line 651 "src/gemfile/parser.y"
{
    gf->_current_groups = realloc(gf->_current_groups,
        sizeof(char *) * (size_t)(gf->_n_current_groups + 1));
    gf->_current_groups[gf->_n_current_groups] = tok_strdup(yymsp[0].minor.yy0, 1, 1);
    gf->_n_current_groups++;
}
#line 1969 "src/gemfile/parser.c"
}
        break;
      case 39: /* platforms_open ::= PLATFORMS platform_names DO */
#line 669 "src/gemfile/parser.y"
{
    /* platform_names already populated gf->_current_platforms */
}
#line 1977 "src/gemfile/parser.c"
  yy_destructor(yypParser,77,&yymsp[-1].minor);
        break;
      case 40: /* platforms_stmt ::= platforms_open stmts END */
{  yy_destructor(yypParser,76,&yymsp[-2].minor);
#line 673 "src/gemfile/parser.y"
{
    /* Clear current platforms */
    for (int i = 0; i < gf->_n_current_platforms; i++)
        free(gf->_current_platforms[i]);
    free(gf->_current_platforms);
    gf->_current_platforms = NULL;
    gf->_n_current_platforms = 0;
}
#line 1991 "src/gemfile/parser.c"
  yy_destructor(yypParser,59,&yymsp[-1].minor);
}
        break;
      case 41: /* platform_names ::= SYMBOL */
#line 682 "src/gemfile/parser.y"
{
    gf->_current_platforms = malloc(sizeof(char *));
    gf->_current_platforms[0] = tok_strdup(yymsp[0].minor.yy0, 1, 0);  /* strip leading colon */
    gf->_n_current_platforms = 1;
}
#line 2002 "src/gemfile/parser.c"
        break;
      case 42: /* platform_names ::= platform_names COMMA SYMBOL */
{  yy_destructor(yypParser,77,&yymsp[-2].minor);
#line 688 "src/gemfile/parser.y"
{
    gf->_current_platforms = realloc(gf->_current_platforms,
        sizeof(char *) * (size_t)(gf->_n_current_platforms + 1));
    gf->_current_platforms[gf->_n_current_platforms] = tok_strdup(yymsp[0].minor.yy0, 1, 0);
    gf->_n_current_platforms++;
}
#line 2013 "src/gemfile/parser.c"
}
        break;
      case 43: /* ruby_stmt ::= RUBY STRING ruby_opts */
#line 723 "src/gemfile/parser.y"
{
    free(gf->ruby_version);
    gf->ruby_version = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
    gem_opts_acc_free(&yymsp[0].minor.yy50);
}
#line 2023 "src/gemfile/parser.c"
        break;
      case 44: /* ruby_stmt ::= RUBY KEY STRING */
#line 729 "src/gemfile/parser.y"
{
    /* ruby file: ".ruby-version" -- accept but don't store version */
}
#line 2030 "src/gemfile/parser.c"
        break;
      case 46: /* ruby_opts ::= ruby_opts COMMA KEY STRING */
      case 47: /* ruby_opts ::= ruby_opts COMMA KEY SYMBOL */ yytestcase(yyruleno==47);
#line 738 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-3].minor.yy50;
    memset(&yymsp[-3].minor.yy50, 0, sizeof(yymsp[-3].minor.yy50));
}
#line 2039 "src/gemfile/parser.c"
  yymsp[-3].minor.yy50 = yylhsminor.yy50;
        break;
      case 48: /* ruby_opts ::= ruby_opts COMMA STRING */
#line 748 "src/gemfile/parser.y"
{
    yylhsminor.yy50 = yymsp[-2].minor.yy50;
    memset(&yymsp[-2].minor.yy50, 0, sizeof(yymsp[-2].minor.yy50));
    /* ruby "~> 3.2", ">= 3.2.1" -- version constraints, ignored */
}
#line 2049 "src/gemfile/parser.c"
  yymsp[-2].minor.yy50 = yylhsminor.yy50;
        break;
      case 49: /* gemspec_stmt ::= GEMSPEC gemspec_opts */
#line 758 "src/gemfile/parser.y"
{
    gf->has_gemspec = true;
}
#line 2057 "src/gemfile/parser.c"
  yy_destructor(yypParser,79,&yymsp[0].minor);
        break;
      case 50: /* file ::= stmts */
{  yy_destructor(yypParser,59,&yymsp[0].minor);
#line 181 "src/gemfile/parser.y"
{
}
#line 2065 "src/gemfile/parser.c"
}
        break;
      case 51: /* stmts ::= stmts stmt */
{  yy_destructor(yypParser,59,&yymsp[-1].minor);
#line 183 "src/gemfile/parser.y"
{
}
#line 2073 "src/gemfile/parser.c"
  yy_destructor(yypParser,60,&yymsp[0].minor);
}
        break;
      case 53: /* stmt ::= source_stmt */
{  yy_destructor(yypParser,61,&yymsp[0].minor);
#line 186 "src/gemfile/parser.y"
{
}
#line 2082 "src/gemfile/parser.c"
}
        break;
      case 54: /* stmt ::= gem_stmt */
{  yy_destructor(yypParser,62,&yymsp[0].minor);
#line 187 "src/gemfile/parser.y"
{
}
#line 2090 "src/gemfile/parser.c"
}
        break;
      case 55: /* stmt ::= group_stmt */
{  yy_destructor(yypParser,63,&yymsp[0].minor);
#line 188 "src/gemfile/parser.y"
{
}
#line 2098 "src/gemfile/parser.c"
}
        break;
      case 56: /* stmt ::= ruby_stmt */
{  yy_destructor(yypParser,64,&yymsp[0].minor);
#line 189 "src/gemfile/parser.y"
{
}
#line 2106 "src/gemfile/parser.c"
}
        break;
      case 57: /* stmt ::= gemspec_stmt */
{  yy_destructor(yypParser,65,&yymsp[0].minor);
#line 190 "src/gemfile/parser.y"
{
}
#line 2114 "src/gemfile/parser.c"
}
        break;
      case 58: /* stmt ::= platforms_stmt */
{  yy_destructor(yypParser,66,&yymsp[0].minor);
#line 191 "src/gemfile/parser.y"
{
}
#line 2122 "src/gemfile/parser.c"
}
        break;
      case 59: /* stmt ::= plugin_stmt */
{  yy_destructor(yypParser,67,&yymsp[0].minor);
#line 192 "src/gemfile/parser.y"
{
}
#line 2130 "src/gemfile/parser.c"
}
        break;
      case 60: /* stmt ::= path_stmt */
{  yy_destructor(yypParser,68,&yymsp[0].minor);
#line 193 "src/gemfile/parser.y"
{
}
#line 2138 "src/gemfile/parser.c"
}
        break;
      case 61: /* stmt ::= git_stmt */
{  yy_destructor(yypParser,69,&yymsp[0].minor);
#line 194 "src/gemfile/parser.y"
{
}
#line 2146 "src/gemfile/parser.c"
}
        break;
      case 62: /* stmt ::= github_stmt */
{  yy_destructor(yypParser,70,&yymsp[0].minor);
#line 195 "src/gemfile/parser.y"
{
}
#line 2154 "src/gemfile/parser.c"
}
        break;
      case 63: /* stmt ::= install_if_stmt */
{  yy_destructor(yypParser,71,&yymsp[0].minor);
#line 196 "src/gemfile/parser.y"
{
}
#line 2162 "src/gemfile/parser.c"
}
        break;
      case 66: /* name_list ::= name_list COMMA KEY LIT_TRUE */
      case 67: /* name_list ::= name_list COMMA KEY LIT_FALSE */ yytestcase(yyruleno==67);
      case 68: /* name_list ::= name_list COMMA KEY STRING */ yytestcase(yyruleno==68);
      case 69: /* name_list ::= name_list COMMA KEY SYMBOL */ yytestcase(yyruleno==69);
{  yy_destructor(yypParser,75,&yymsp[-3].minor);
#line 659 "src/gemfile/parser.y"
{
}
#line 2173 "src/gemfile/parser.c"
}
        break;
      case 71: /* block_kw_opts ::= block_kw_opts COMMA KEY STRING */
      case 72: /* block_kw_opts ::= block_kw_opts COMMA KEY SYMBOL */ yytestcase(yyruleno==72);
      case 73: /* block_kw_opts ::= block_kw_opts COMMA KEY LIT_TRUE */ yytestcase(yyruleno==73);
      case 74: /* block_kw_opts ::= block_kw_opts COMMA KEY LIT_FALSE */ yytestcase(yyruleno==74);
{  yy_destructor(yypParser,78,&yymsp[-3].minor);
#line 703 "src/gemfile/parser.y"
{
}
#line 2184 "src/gemfile/parser.c"
}
        break;
      case 75: /* path_stmt ::= PATH STRING block_kw_opts DO stmts END */
      case 76: /* git_stmt ::= GIT STRING block_kw_opts DO stmts END */ yytestcase(yyruleno==76);
      case 77: /* github_stmt ::= GITHUB STRING block_kw_opts DO stmts END */ yytestcase(yyruleno==77);
#line 708 "src/gemfile/parser.y"
{
}
#line 2193 "src/gemfile/parser.c"
  yy_destructor(yypParser,78,&yymsp[-3].minor);
  yy_destructor(yypParser,59,&yymsp[-1].minor);
        break;
      case 78: /* install_if_stmt ::= INSTALL_IF DO stmts END */
#line 716 "src/gemfile/parser.y"
{
}
#line 2201 "src/gemfile/parser.c"
  yy_destructor(yypParser,59,&yymsp[-1].minor);
        break;
      case 80: /* gemspec_opts ::= gemspec_opts COMMA KEY STRING */
      case 81: /* gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */ yytestcase(yyruleno==81);
{  yy_destructor(yypParser,79,&yymsp[-3].minor);
#line 765 "src/gemfile/parser.y"
{
}
#line 2210 "src/gemfile/parser.c"
}
        break;
      case 86: /* gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
      case 87: /* gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */ yytestcase(yyruleno==87);
{  yy_destructor(yypParser,79,&yymsp[-4].minor);
#line 775 "src/gemfile/parser.y"
{
}
#line 2219 "src/gemfile/parser.c"
}
        break;
      default:
      /* (52) stmts ::= */ yytestcase(yyruleno==52);
      /* (64) stmt ::= GIT_SOURCE */ yytestcase(yyruleno==64);
      /* (65) stmt ::= NEWLINE */ yytestcase(yyruleno==65);
      /* (70) block_kw_opts ::= */ yytestcase(yyruleno==70);
      /* (79) gemspec_opts ::= */ yytestcase(yyruleno==79);
      /* (82) gemspec_opts ::= KEY STRING */ yytestcase(yyruleno==82);
      /* (83) gemspec_opts ::= KEY SYMBOL */ yytestcase(yyruleno==83);
      /* (84) gemspec_opts ::= SYMBOL HASHROCKET STRING */ yytestcase(yyruleno==84);
      /* (85) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */ yytestcase(yyruleno==85);
      /* (88) plugin_stmt ::= PLUGIN STRING */ yytestcase(yyruleno==88);
      /* (89) plugin_stmt ::= PLUGIN STRING COMMA STRING */ yytestcase(yyruleno==89);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 173 "src/gemfile/parser.y"

    fprintf(stderr, "wow: Gemfile parsing failed\n");
#line 2278 "src/gemfile/parser.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 165 "src/gemfile/parser.y"

    (void)yymajor;
    (void)yyminor;
    fprintf(stderr, "wow: Gemfile syntax error at line %d\n",
            TOKEN.line);
    gf->_deps_cap = (size_t)-1;  /* signal error */
#line 2304 "src/gemfile/parser.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
