#define SOURCE                           1
#define GEM                              2
#define GROUP                            3
#define DO                               4
#define END                              5
#define RUBY                             6
#define GEMSPEC                          7
#define LIT_TRUE                         8
#define LIT_FALSE                        9
#define LIT_NIL                         10
#define STRING                          11
#define SYMBOL                          12
#define KEY                             13
#define COMMA                           14
#define HASHROCKET                      15
#define NEWLINE                         16
#define IDENT                           17
#define UNSUPPORTED                     18
#define ERROR                           19
#define GIT_SOURCE                      20
#define PLUGIN                          21
#define PLATFORMS                       22
#define LBRACKET                        23
#define RBRACKET                        24
#define LPAREN                          25
#define RPAREN                          26
#define PERCENT_ARRAY                   27
