/* This file is automatically generated by Lemon from input grammar
** source file "src/gemfile/parser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 11 "src/gemfile/parser.y"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "wow/gemfile/lexer.h"
#include "wow/gemfile/types.h"

/*
 * Helper: duplicate a token's text, stripping leading/trailing chars.
 * strip_left/strip_right indicate how many chars to remove from each end.
 * For STRING tokens: strip 1 from each side (the quotes).
 * For SYMBOL tokens: strip 1 from left (the colon).
 * For KEY tokens: strip 1 from right (the colon).
 */
static char *tok_strdup(struct wow_token t, int strip_left, int strip_right)
{
    int len = t.length - strip_left - strip_right;
    if (len <= 0) return strdup("");
    return strndup(t.start + strip_left, (size_t)len);
}

/*
 * Accumulator for gem_opts: collects version constraints + keyword
 * options as the parser reduces gem_opts rules left-to-right.
 */
struct gem_opts_acc {
    char **constraints;
    int    n_constraints;
    int    constraints_cap;
    char  *group;
    bool   require;
};

static void gem_opts_acc_init(struct gem_opts_acc *a)
{
    memset(a, 0, sizeof(*a));
    a->require = true;
}

static void gem_opts_acc_add_constraint(struct gem_opts_acc *a, char *s)
{
    if (a->n_constraints >= a->constraints_cap) {
        a->constraints_cap = a->constraints_cap ? a->constraints_cap * 2 : 4;
        a->constraints = realloc(a->constraints,
                                 sizeof(char *) * (size_t)a->constraints_cap);
    }
    a->constraints[a->n_constraints++] = s;
}

static void gem_opts_acc_free(struct gem_opts_acc *a)
{
    for (int i = 0; i < a->n_constraints; i++)
        free(a->constraints[i]);
    free(a->constraints);
    free(a->group);
}

#line 90 "src/gemfile/parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef SOURCE
#define SOURCE                          1
#define GEM                             2
#define GROUP                           3
#define DO                              4
#define END                             5
#define RUBY                            6
#define GEMSPEC                         7
#define LIT_TRUE                        8
#define LIT_FALSE                       9
#define LIT_NIL                        10
#define STRING                         11
#define SYMBOL                         12
#define KEY                            13
#define COMMA                          14
#define HASHROCKET                     15
#define NEWLINE                        16
#define IDENT                          17
#define UNSUPPORTED                    18
#define ERROR                          19
#define GIT_SOURCE                     20
#define PLUGIN                         21
#define PLATFORMS                      22
#define LBRACKET                       23
#define RBRACKET                       24
#define LPAREN                         25
#define RPAREN                         26
#define PERCENT_ARRAY                  27
#define IF                             28
#define UNLESS                         29
#define ELSE                           30
#define ELSIF                          31
#define EVAL_GEMFILE                   32
#define EQ                             33
#define NEQ                            34
#define GTE                            35
#define LTE                            36
#define GT                             37
#define LT                             38
#define MATCH                          39
#define AND                            40
#define OR                             41
#define BANG                           42
#define ASSIGN                         43
#define DOT                            44
#define COLON_COLON                    45
#define PIPE                           46
#define QUESTION                       47
#define INTEGER                        48
#define FLOAT_LIT                      49
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 69
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE  struct wow_token 
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  struct gem_opts_acc yy96;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  struct wow_gemfile *gf ;
#define ParseARG_PDECL , struct wow_gemfile *gf 
#define ParseARG_PARAM ,gf 
#define ParseARG_FETCH  struct wow_gemfile *gf =yypParser->gf ;
#define ParseARG_STORE yypParser->gf =gf ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             49
#define YYNRULE              67
#define YYNRULE_WITH_ACTION  34
#define YYNTOKEN             50
#define YY_MAX_SHIFT         48
#define YY_MIN_SHIFTREDUCE   106
#define YY_MAX_SHIFTREDUCE   172
#define YY_ERROR_ACTION      173
#define YY_ACCEPT_ACTION     174
#define YY_NO_ACTION         175
#define YY_MIN_REDUCE        176
#define YY_MAX_REDUCE        242
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (140)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   194,   18,   47,    7,  188,  132,   26,    9,  174,    4,
 /*    10 */    30,   32,   40,  112,   45,    6,  151,  129,  128,   28,
 /*    20 */   150,   37,   11,  211,  211,  211,  211,  211,  211,  211,
 /*    30 */   211,   10,  138,   14,   24,   13,  160,   18,   47,    7,
 /*    40 */    27,  127,   26,    9,   18,   47,    7,   42,  108,   26,
 /*    50 */     9,   12,  151,   41,   38,   20,  150,   37,   11,  151,
 /*    60 */     1,  156,  155,  150,   37,   11,  210,   18,   47,    7,
 /*    70 */    48,  107,   26,    9,  153,  120,  119,  121,  123,  122,
 /*    80 */   129,  128,  151,  159,   34,    2,  150,   37,   11,   46,
 /*    90 */     8,  167,  168,   43,  154,  114,  113,  115,  117,  116,
 /*   100 */   165,  166,  169,  170,  163,  164,   29,   39,   22,  125,
 /*   110 */     8,  136,  137,   31,  154,  131,  130,    3,   44,   29,
 /*   120 */   158,  157,  109,  152,   33,  172,   35,   36,  126,  134,
 /*   130 */    19,   16,   21,   23,   25,  161,    5,   15,  175,   17,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    62,    1,    2,    3,   62,    5,    6,    7,   52,   53,
 /*    10 */    65,   63,   68,   11,   12,   13,   16,   11,   12,   65,
 /*    20 */    20,   21,   22,   54,   55,   56,   57,   58,   59,   60,
 /*    30 */    61,   25,   11,   64,   13,   66,   12,    1,    2,    3,
 /*    40 */    67,    5,    6,    7,    1,    2,    3,   51,    5,    6,
 /*    50 */     7,   11,   16,   13,   12,   13,   20,   21,   22,   16,
 /*    60 */    53,   11,   12,   20,   21,   22,    0,    1,    2,    3,
 /*    70 */    11,   12,    6,    7,   24,    8,    9,   10,   11,   12,
 /*    80 */    11,   12,   16,    4,   25,   53,   20,   21,   22,   50,
 /*    90 */    23,   11,   12,   14,   27,    8,    9,   10,   11,   12,
 /*   100 */    11,   12,   11,   12,   11,   12,   14,   12,   13,    4,
 /*   110 */    23,   11,   12,   14,   27,   11,   12,   53,   26,   14,
 /*   120 */    11,   12,   26,   24,   11,   11,   14,   11,    4,   11,
 /*   130 */    15,    4,   15,   14,   14,   12,   15,   11,   69,   14,
 /*   140 */    69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
 /*   150 */    69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
 /*   160 */    69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
 /*   170 */    69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
 /*   180 */    69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
};
#define YY_SHIFT_COUNT    (48)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (127)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */   140,    0,   36,   43,   66,   67,   87,    6,   50,   42,
 /*    10 */    69,   24,  140,  140,  140,  140,  140,    2,   59,   80,
 /*    20 */    89,   91,   93,   95,  100,   21,   40,   79,   92,  104,
 /*    30 */   105,  109,   99,   96,  113,  114,  112,  116,  115,  117,
 /*    40 */   119,  118,  120,  123,  124,  121,  125,  126,  127,
};
#define YY_REDUCE_COUNT (16)
#define YY_REDUCE_MIN   (-62)
#define YY_REDUCE_MAX   (64)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -44,  -31,  -31,  -31,  -31,  -62,  -58,  -55,  -52,  -56,
 /*    10 */   -46,  -27,   -4,    7,   32,   39,   64,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   212,  173,  173,  173,  173,  173,  173,  173,  173,  232,
 /*    10 */   173,  173,  205,  212,  212,  181,  212,  173,  173,  173,
 /*    20 */   173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
 /*    30 */   173,  173,  173,  173,  173,  173,  241,  173,  173,  173,
 /*    40 */   209,  173,  203,  173,  173,  173,  180,  173,  176,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "SOURCE",
  /*    2 */ "GEM",
  /*    3 */ "GROUP",
  /*    4 */ "DO",
  /*    5 */ "END",
  /*    6 */ "RUBY",
  /*    7 */ "GEMSPEC",
  /*    8 */ "LIT_TRUE",
  /*    9 */ "LIT_FALSE",
  /*   10 */ "LIT_NIL",
  /*   11 */ "STRING",
  /*   12 */ "SYMBOL",
  /*   13 */ "KEY",
  /*   14 */ "COMMA",
  /*   15 */ "HASHROCKET",
  /*   16 */ "NEWLINE",
  /*   17 */ "IDENT",
  /*   18 */ "UNSUPPORTED",
  /*   19 */ "ERROR",
  /*   20 */ "GIT_SOURCE",
  /*   21 */ "PLUGIN",
  /*   22 */ "PLATFORMS",
  /*   23 */ "LBRACKET",
  /*   24 */ "RBRACKET",
  /*   25 */ "LPAREN",
  /*   26 */ "RPAREN",
  /*   27 */ "PERCENT_ARRAY",
  /*   28 */ "IF",
  /*   29 */ "UNLESS",
  /*   30 */ "ELSE",
  /*   31 */ "ELSIF",
  /*   32 */ "EVAL_GEMFILE",
  /*   33 */ "EQ",
  /*   34 */ "NEQ",
  /*   35 */ "GTE",
  /*   36 */ "LTE",
  /*   37 */ "GT",
  /*   38 */ "LT",
  /*   39 */ "MATCH",
  /*   40 */ "AND",
  /*   41 */ "OR",
  /*   42 */ "BANG",
  /*   43 */ "ASSIGN",
  /*   44 */ "DOT",
  /*   45 */ "COLON_COLON",
  /*   46 */ "PIPE",
  /*   47 */ "QUESTION",
  /*   48 */ "INTEGER",
  /*   49 */ "FLOAT_LIT",
  /*   50 */ "gem_opts",
  /*   51 */ "ruby_opts",
  /*   52 */ "file",
  /*   53 */ "stmts",
  /*   54 */ "stmt",
  /*   55 */ "source_stmt",
  /*   56 */ "gem_stmt",
  /*   57 */ "group_stmt",
  /*   58 */ "ruby_stmt",
  /*   59 */ "gemspec_stmt",
  /*   60 */ "platforms_stmt",
  /*   61 */ "plugin_stmt",
  /*   62 */ "array",
  /*   63 */ "array_items",
  /*   64 */ "group_open",
  /*   65 */ "name_list",
  /*   66 */ "platforms_open",
  /*   67 */ "platform_names",
  /*   68 */ "gemspec_opts",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "source_stmt ::= SOURCE STRING",
 /*   1 */ "source_stmt ::= SOURCE SYMBOL",
 /*   2 */ "source_stmt ::= SOURCE STRING DO stmts END",
 /*   3 */ "source_stmt ::= SOURCE LPAREN STRING RPAREN",
 /*   4 */ "gem_stmt ::= GEM STRING gem_opts",
 /*   5 */ "gem_opts ::=",
 /*   6 */ "gem_opts ::= gem_opts COMMA STRING",
 /*   7 */ "gem_opts ::= gem_opts COMMA KEY LIT_FALSE",
 /*   8 */ "gem_opts ::= gem_opts COMMA KEY LIT_TRUE",
 /*   9 */ "gem_opts ::= gem_opts COMMA KEY LIT_NIL",
 /*  10 */ "gem_opts ::= gem_opts COMMA KEY SYMBOL",
 /*  11 */ "gem_opts ::= gem_opts COMMA KEY STRING",
 /*  12 */ "gem_opts ::= gem_opts COMMA KEY array",
 /*  13 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE",
 /*  14 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE",
 /*  15 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL",
 /*  16 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL",
 /*  17 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING",
 /*  18 */ "gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET array",
 /*  19 */ "group_open ::= GROUP name_list DO",
 /*  20 */ "group_open ::= GROUP LPAREN name_list RPAREN DO",
 /*  21 */ "group_stmt ::= group_open stmts END",
 /*  22 */ "name_list ::= SYMBOL",
 /*  23 */ "name_list ::= STRING",
 /*  24 */ "name_list ::= name_list COMMA SYMBOL",
 /*  25 */ "name_list ::= name_list COMMA STRING",
 /*  26 */ "platforms_stmt ::= platforms_open stmts END",
 /*  27 */ "ruby_stmt ::= RUBY STRING ruby_opts",
 /*  28 */ "ruby_stmt ::= RUBY KEY STRING",
 /*  29 */ "ruby_opts ::=",
 /*  30 */ "ruby_opts ::= ruby_opts COMMA KEY STRING",
 /*  31 */ "ruby_opts ::= ruby_opts COMMA KEY SYMBOL",
 /*  32 */ "ruby_opts ::= ruby_opts COMMA STRING",
 /*  33 */ "gemspec_stmt ::= GEMSPEC gemspec_opts",
 /*  34 */ "file ::= stmts",
 /*  35 */ "stmts ::= stmts stmt",
 /*  36 */ "stmts ::=",
 /*  37 */ "stmt ::= source_stmt",
 /*  38 */ "stmt ::= gem_stmt",
 /*  39 */ "stmt ::= group_stmt",
 /*  40 */ "stmt ::= ruby_stmt",
 /*  41 */ "stmt ::= gemspec_stmt",
 /*  42 */ "stmt ::= platforms_stmt",
 /*  43 */ "stmt ::= plugin_stmt",
 /*  44 */ "stmt ::= GIT_SOURCE",
 /*  45 */ "stmt ::= NEWLINE",
 /*  46 */ "array ::= LBRACKET array_items RBRACKET",
 /*  47 */ "array ::= LBRACKET RBRACKET",
 /*  48 */ "array ::= PERCENT_ARRAY",
 /*  49 */ "array_items ::= SYMBOL",
 /*  50 */ "array_items ::= STRING",
 /*  51 */ "array_items ::= array_items COMMA SYMBOL",
 /*  52 */ "array_items ::= array_items COMMA STRING",
 /*  53 */ "platforms_open ::= PLATFORMS platform_names DO",
 /*  54 */ "platform_names ::= SYMBOL",
 /*  55 */ "platform_names ::= platform_names COMMA SYMBOL",
 /*  56 */ "gemspec_opts ::=",
 /*  57 */ "gemspec_opts ::= gemspec_opts COMMA KEY STRING",
 /*  58 */ "gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL",
 /*  59 */ "gemspec_opts ::= KEY STRING",
 /*  60 */ "gemspec_opts ::= KEY SYMBOL",
 /*  61 */ "gemspec_opts ::= SYMBOL HASHROCKET STRING",
 /*  62 */ "gemspec_opts ::= SYMBOL HASHROCKET SYMBOL",
 /*  63 */ "gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING",
 /*  64 */ "gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL",
 /*  65 */ "plugin_stmt ::= PLUGIN STRING",
 /*  66 */ "plugin_stmt ::= PLUGIN STRING COMMA STRING",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* Default NON-TERMINAL Destructor */
    case 52: /* file */
    case 53: /* stmts */
    case 54: /* stmt */
    case 55: /* source_stmt */
    case 56: /* gem_stmt */
    case 57: /* group_stmt */
    case 58: /* ruby_stmt */
    case 59: /* gemspec_stmt */
    case 60: /* platforms_stmt */
    case 61: /* plugin_stmt */
    case 62: /* array */
    case 63: /* array_items */
    case 64: /* group_open */
    case 65: /* name_list */
    case 66: /* platforms_open */
    case 67: /* platform_names */
    case 68: /* gemspec_opts */
{
#line 76 "src/gemfile/parser.y"
 (void)(yypminor->yy0); (void)gf; 
#line 758 "src/gemfile/parser.c"
}
      break;
    case 50: /* gem_opts */
    case 51: /* ruby_opts */
{
#line 86 "src/gemfile/parser.y"
 gem_opts_acc_free(&(yypminor->yy96)); 
#line 766 "src/gemfile/parser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    55,  /* (0) source_stmt ::= SOURCE STRING */
    55,  /* (1) source_stmt ::= SOURCE SYMBOL */
    55,  /* (2) source_stmt ::= SOURCE STRING DO stmts END */
    55,  /* (3) source_stmt ::= SOURCE LPAREN STRING RPAREN */
    56,  /* (4) gem_stmt ::= GEM STRING gem_opts */
    50,  /* (5) gem_opts ::= */
    50,  /* (6) gem_opts ::= gem_opts COMMA STRING */
    50,  /* (7) gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
    50,  /* (8) gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
    50,  /* (9) gem_opts ::= gem_opts COMMA KEY LIT_NIL */
    50,  /* (10) gem_opts ::= gem_opts COMMA KEY SYMBOL */
    50,  /* (11) gem_opts ::= gem_opts COMMA KEY STRING */
    50,  /* (12) gem_opts ::= gem_opts COMMA KEY array */
    50,  /* (13) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
    50,  /* (14) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
    50,  /* (15) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
    50,  /* (16) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
    50,  /* (17) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
    50,  /* (18) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET array */
    64,  /* (19) group_open ::= GROUP name_list DO */
    64,  /* (20) group_open ::= GROUP LPAREN name_list RPAREN DO */
    57,  /* (21) group_stmt ::= group_open stmts END */
    65,  /* (22) name_list ::= SYMBOL */
    65,  /* (23) name_list ::= STRING */
    65,  /* (24) name_list ::= name_list COMMA SYMBOL */
    65,  /* (25) name_list ::= name_list COMMA STRING */
    60,  /* (26) platforms_stmt ::= platforms_open stmts END */
    58,  /* (27) ruby_stmt ::= RUBY STRING ruby_opts */
    58,  /* (28) ruby_stmt ::= RUBY KEY STRING */
    51,  /* (29) ruby_opts ::= */
    51,  /* (30) ruby_opts ::= ruby_opts COMMA KEY STRING */
    51,  /* (31) ruby_opts ::= ruby_opts COMMA KEY SYMBOL */
    51,  /* (32) ruby_opts ::= ruby_opts COMMA STRING */
    59,  /* (33) gemspec_stmt ::= GEMSPEC gemspec_opts */
    52,  /* (34) file ::= stmts */
    53,  /* (35) stmts ::= stmts stmt */
    53,  /* (36) stmts ::= */
    54,  /* (37) stmt ::= source_stmt */
    54,  /* (38) stmt ::= gem_stmt */
    54,  /* (39) stmt ::= group_stmt */
    54,  /* (40) stmt ::= ruby_stmt */
    54,  /* (41) stmt ::= gemspec_stmt */
    54,  /* (42) stmt ::= platforms_stmt */
    54,  /* (43) stmt ::= plugin_stmt */
    54,  /* (44) stmt ::= GIT_SOURCE */
    54,  /* (45) stmt ::= NEWLINE */
    62,  /* (46) array ::= LBRACKET array_items RBRACKET */
    62,  /* (47) array ::= LBRACKET RBRACKET */
    62,  /* (48) array ::= PERCENT_ARRAY */
    63,  /* (49) array_items ::= SYMBOL */
    63,  /* (50) array_items ::= STRING */
    63,  /* (51) array_items ::= array_items COMMA SYMBOL */
    63,  /* (52) array_items ::= array_items COMMA STRING */
    66,  /* (53) platforms_open ::= PLATFORMS platform_names DO */
    67,  /* (54) platform_names ::= SYMBOL */
    67,  /* (55) platform_names ::= platform_names COMMA SYMBOL */
    68,  /* (56) gemspec_opts ::= */
    68,  /* (57) gemspec_opts ::= gemspec_opts COMMA KEY STRING */
    68,  /* (58) gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */
    68,  /* (59) gemspec_opts ::= KEY STRING */
    68,  /* (60) gemspec_opts ::= KEY SYMBOL */
    68,  /* (61) gemspec_opts ::= SYMBOL HASHROCKET STRING */
    68,  /* (62) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */
    68,  /* (63) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
    68,  /* (64) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */
    61,  /* (65) plugin_stmt ::= PLUGIN STRING */
    61,  /* (66) plugin_stmt ::= PLUGIN STRING COMMA STRING */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -2,  /* (0) source_stmt ::= SOURCE STRING */
   -2,  /* (1) source_stmt ::= SOURCE SYMBOL */
   -5,  /* (2) source_stmt ::= SOURCE STRING DO stmts END */
   -4,  /* (3) source_stmt ::= SOURCE LPAREN STRING RPAREN */
   -3,  /* (4) gem_stmt ::= GEM STRING gem_opts */
    0,  /* (5) gem_opts ::= */
   -3,  /* (6) gem_opts ::= gem_opts COMMA STRING */
   -4,  /* (7) gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
   -4,  /* (8) gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
   -4,  /* (9) gem_opts ::= gem_opts COMMA KEY LIT_NIL */
   -4,  /* (10) gem_opts ::= gem_opts COMMA KEY SYMBOL */
   -4,  /* (11) gem_opts ::= gem_opts COMMA KEY STRING */
   -4,  /* (12) gem_opts ::= gem_opts COMMA KEY array */
   -5,  /* (13) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
   -5,  /* (14) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
   -5,  /* (15) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
   -5,  /* (16) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
   -5,  /* (17) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
   -5,  /* (18) gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET array */
   -3,  /* (19) group_open ::= GROUP name_list DO */
   -5,  /* (20) group_open ::= GROUP LPAREN name_list RPAREN DO */
   -3,  /* (21) group_stmt ::= group_open stmts END */
   -1,  /* (22) name_list ::= SYMBOL */
   -1,  /* (23) name_list ::= STRING */
   -3,  /* (24) name_list ::= name_list COMMA SYMBOL */
   -3,  /* (25) name_list ::= name_list COMMA STRING */
   -3,  /* (26) platforms_stmt ::= platforms_open stmts END */
   -3,  /* (27) ruby_stmt ::= RUBY STRING ruby_opts */
   -3,  /* (28) ruby_stmt ::= RUBY KEY STRING */
    0,  /* (29) ruby_opts ::= */
   -4,  /* (30) ruby_opts ::= ruby_opts COMMA KEY STRING */
   -4,  /* (31) ruby_opts ::= ruby_opts COMMA KEY SYMBOL */
   -3,  /* (32) ruby_opts ::= ruby_opts COMMA STRING */
   -2,  /* (33) gemspec_stmt ::= GEMSPEC gemspec_opts */
   -1,  /* (34) file ::= stmts */
   -2,  /* (35) stmts ::= stmts stmt */
    0,  /* (36) stmts ::= */
   -1,  /* (37) stmt ::= source_stmt */
   -1,  /* (38) stmt ::= gem_stmt */
   -1,  /* (39) stmt ::= group_stmt */
   -1,  /* (40) stmt ::= ruby_stmt */
   -1,  /* (41) stmt ::= gemspec_stmt */
   -1,  /* (42) stmt ::= platforms_stmt */
   -1,  /* (43) stmt ::= plugin_stmt */
   -1,  /* (44) stmt ::= GIT_SOURCE */
   -1,  /* (45) stmt ::= NEWLINE */
   -3,  /* (46) array ::= LBRACKET array_items RBRACKET */
   -2,  /* (47) array ::= LBRACKET RBRACKET */
   -1,  /* (48) array ::= PERCENT_ARRAY */
   -1,  /* (49) array_items ::= SYMBOL */
   -1,  /* (50) array_items ::= STRING */
   -3,  /* (51) array_items ::= array_items COMMA SYMBOL */
   -3,  /* (52) array_items ::= array_items COMMA STRING */
   -3,  /* (53) platforms_open ::= PLATFORMS platform_names DO */
   -1,  /* (54) platform_names ::= SYMBOL */
   -3,  /* (55) platform_names ::= platform_names COMMA SYMBOL */
    0,  /* (56) gemspec_opts ::= */
   -4,  /* (57) gemspec_opts ::= gemspec_opts COMMA KEY STRING */
   -4,  /* (58) gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */
   -2,  /* (59) gemspec_opts ::= KEY STRING */
   -2,  /* (60) gemspec_opts ::= KEY SYMBOL */
   -3,  /* (61) gemspec_opts ::= SYMBOL HASHROCKET STRING */
   -3,  /* (62) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */
   -5,  /* (63) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
   -5,  /* (64) gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */
   -2,  /* (65) plugin_stmt ::= PLUGIN STRING */
   -4,  /* (66) plugin_stmt ::= PLUGIN STRING COMMA STRING */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* source_stmt ::= SOURCE STRING */
#line 144 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[0].minor.yy0, 1, 1);
}
#line 1241 "src/gemfile/parser.c"
        break;
      case 1: /* source_stmt ::= SOURCE SYMBOL */
#line 150 "src/gemfile/parser.y"
{
    free(gf->source);
    char *sym = tok_strdup(yymsp[0].minor.yy0, 1, 0);  /* strip leading colon */
    if (strcmp(sym, "rubygems") == 0 || strcmp(sym, "gemcutter") == 0) {
        gf->source = strdup("https://rubygems.org");
        free(sym);
    } else {
        gf->source = sym;  /* unknown symbol -- store as-is */
    }
}
#line 1255 "src/gemfile/parser.c"
        break;
      case 2: /* source_stmt ::= SOURCE STRING DO stmts END */
#line 164 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[-3].minor.yy0, 1, 1);
}
#line 1263 "src/gemfile/parser.c"
  yy_destructor(yypParser,53,&yymsp[-1].minor);
        break;
      case 3: /* source_stmt ::= SOURCE LPAREN STRING RPAREN */
#line 170 "src/gemfile/parser.y"
{
    free(gf->source);
    gf->source = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
}
#line 1272 "src/gemfile/parser.c"
        break;
      case 4: /* gem_stmt ::= GEM STRING gem_opts */
#line 179 "src/gemfile/parser.y"
{
    struct wow_gemfile_dep dep;
    memset(&dep, 0, sizeof(dep));
    dep.name          = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
    dep.constraints   = yymsp[0].minor.yy96.constraints;
    dep.n_constraints = yymsp[0].minor.yy96.n_constraints;
    dep.require       = yymsp[0].minor.yy96.require;

    /* group: keyword option takes priority over block group */
    if (yymsp[0].minor.yy96.group) {
        dep.group = yymsp[0].minor.yy96.group;
    } else if (gf->_current_group) {
        dep.group = strdup(gf->_current_group);
    }

    /* Prevent gem_opts destructor from freeing transferred pointers */
    yymsp[0].minor.yy96.constraints = NULL;
    yymsp[0].minor.yy96.n_constraints = 0;
    yymsp[0].minor.yy96.group = NULL;

    wow_gemfile_add_dep(gf, &dep);
}
#line 1298 "src/gemfile/parser.c"
        break;
      case 5: /* gem_opts ::= */
      case 29: /* ruby_opts ::= */ yytestcase(yyruleno==29);
#line 203 "src/gemfile/parser.y"
{
    gem_opts_acc_init(&yymsp[1].minor.yy96);
}
#line 1306 "src/gemfile/parser.c"
        break;
      case 6: /* gem_opts ::= gem_opts COMMA STRING */
#line 207 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-2].minor.yy96;
    memset(&yymsp[-2].minor.yy96, 0, sizeof(yymsp[-2].minor.yy96));  /* prevent double-free */
    gem_opts_acc_add_constraint(&yylhsminor.yy96, tok_strdup(yymsp[0].minor.yy0, 1, 1));
}
#line 1315 "src/gemfile/parser.c"
  yymsp[-2].minor.yy96 = yylhsminor.yy96;
        break;
      case 7: /* gem_opts ::= gem_opts COMMA KEY LIT_FALSE */
#line 213 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);  /* strip trailing colon */
    if (strcmp(key, "require") == 0)
        yylhsminor.yy96.require = false;
    free(key);
}
#line 1328 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 8: /* gem_opts ::= gem_opts COMMA KEY LIT_TRUE */
#line 222 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    (void)yymsp[-1].minor.yy0;  /* require: true is the default */
}
#line 1338 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 9: /* gem_opts ::= gem_opts COMMA KEY LIT_NIL */
#line 228 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);
    if (strcmp(key, "require") == 0)
        yylhsminor.yy96.require = false;  /* require: nil == require: false */
    free(key);
}
#line 1351 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 10: /* gem_opts ::= gem_opts COMMA KEY SYMBOL */
#line 237 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    char *key = tok_strdup(yymsp[-1].minor.yy0, 0, 1);  /* strip trailing colon */
    if (strcmp(key, "group") == 0 || strcmp(key, "groups") == 0) {
        free(yylhsminor.yy96.group);
        yylhsminor.yy96.group = tok_strdup(yymsp[0].minor.yy0, 1, 0);  /* strip leading colon */
    }
    free(key);
}
#line 1366 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 11: /* gem_opts ::= gem_opts COMMA KEY STRING */
#line 248 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    /* Unknown key with string value -- accept but ignore (path:, git:, etc.) */
}
#line 1376 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 12: /* gem_opts ::= gem_opts COMMA KEY array */
#line 254 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
    /* Key with array value -- accept but ignore (platforms:, groups:, etc.) */
}
#line 1386 "src/gemfile/parser.c"
  yy_destructor(yypParser,62,&yymsp[0].minor);
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 13: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_FALSE */
#line 261 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);  /* strip leading colon */
    if (strcmp(key, "require") == 0)
        yylhsminor.yy96.require = false;
    free(key);
}
#line 1400 "src/gemfile/parser.c"
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 14: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_TRUE */
#line 270 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    (void)yymsp[-2].minor.yy0;
}
#line 1410 "src/gemfile/parser.c"
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 15: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET LIT_NIL */
#line 276 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);
    if (strcmp(key, "require") == 0)
        yylhsminor.yy96.require = false;
    free(key);
}
#line 1423 "src/gemfile/parser.c"
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 16: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET SYMBOL */
#line 285 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    char *key = tok_strdup(yymsp[-2].minor.yy0, 1, 0);
    if (strcmp(key, "group") == 0) {
        free(yylhsminor.yy96.group);
        yylhsminor.yy96.group = tok_strdup(yymsp[0].minor.yy0, 1, 0);
    }
    free(key);
}
#line 1438 "src/gemfile/parser.c"
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 17: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET STRING */
#line 296 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    /* Unknown hashrocket key with string value -- ignore */
}
#line 1448 "src/gemfile/parser.c"
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 18: /* gem_opts ::= gem_opts COMMA SYMBOL HASHROCKET array */
#line 302 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-4].minor.yy96;
    memset(&yymsp[-4].minor.yy96, 0, sizeof(yymsp[-4].minor.yy96));
    /* Hashrocket key with array value -- accept but ignore */
}
#line 1458 "src/gemfile/parser.c"
  yy_destructor(yypParser,62,&yymsp[0].minor);
  yymsp[-4].minor.yy96 = yylhsminor.yy96;
        break;
      case 19: /* group_open ::= GROUP name_list DO */
#line 327 "src/gemfile/parser.y"
{
    /* _current_group was set by name_list reduction */
}
#line 1467 "src/gemfile/parser.c"
  yy_destructor(yypParser,65,&yymsp[-1].minor);
        break;
      case 20: /* group_open ::= GROUP LPAREN name_list RPAREN DO */
#line 331 "src/gemfile/parser.y"
{
    /* _current_group was set by name_list reduction */
}
#line 1475 "src/gemfile/parser.c"
  yy_destructor(yypParser,65,&yymsp[-2].minor);
        break;
      case 21: /* group_stmt ::= group_open stmts END */
{  yy_destructor(yypParser,64,&yymsp[-2].minor);
#line 335 "src/gemfile/parser.y"
{
    free(gf->_current_group);
    gf->_current_group = NULL;
}
#line 1485 "src/gemfile/parser.c"
  yy_destructor(yypParser,53,&yymsp[-1].minor);
}
        break;
      case 22: /* name_list ::= SYMBOL */
#line 340 "src/gemfile/parser.y"
{
    free(gf->_current_group);
    gf->_current_group = tok_strdup(yymsp[0].minor.yy0, 1, 0);  /* strip leading colon */
}
#line 1495 "src/gemfile/parser.c"
        break;
      case 23: /* name_list ::= STRING */
#line 345 "src/gemfile/parser.y"
{
    free(gf->_current_group);
    gf->_current_group = tok_strdup(yymsp[0].minor.yy0, 1, 1);  /* strip quotes */
}
#line 1503 "src/gemfile/parser.c"
        break;
      case 24: /* name_list ::= name_list COMMA SYMBOL */
      case 25: /* name_list ::= name_list COMMA STRING */ yytestcase(yyruleno==25);
{  yy_destructor(yypParser,65,&yymsp[-2].minor);
#line 350 "src/gemfile/parser.y"
{
    /* Keep the first name, ignore subsequent ones */
}
#line 1512 "src/gemfile/parser.c"
}
        break;
      case 26: /* platforms_stmt ::= platforms_open stmts END */
{  yy_destructor(yypParser,66,&yymsp[-2].minor);
#line 365 "src/gemfile/parser.y"
{
    /* Gems inside are collected normally; platform filter is ignored */
}
#line 1521 "src/gemfile/parser.c"
  yy_destructor(yypParser,53,&yymsp[-1].minor);
}
        break;
      case 27: /* ruby_stmt ::= RUBY STRING ruby_opts */
#line 377 "src/gemfile/parser.y"
{
    free(gf->ruby_version);
    gf->ruby_version = tok_strdup(yymsp[-1].minor.yy0, 1, 1);
    gem_opts_acc_free(&yymsp[0].minor.yy96);
}
#line 1532 "src/gemfile/parser.c"
        break;
      case 28: /* ruby_stmt ::= RUBY KEY STRING */
#line 383 "src/gemfile/parser.y"
{
    /* ruby file: ".ruby-version" -- accept but don't store version */
}
#line 1539 "src/gemfile/parser.c"
        break;
      case 30: /* ruby_opts ::= ruby_opts COMMA KEY STRING */
      case 31: /* ruby_opts ::= ruby_opts COMMA KEY SYMBOL */ yytestcase(yyruleno==31);
#line 392 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-3].minor.yy96;
    memset(&yymsp[-3].minor.yy96, 0, sizeof(yymsp[-3].minor.yy96));
}
#line 1548 "src/gemfile/parser.c"
  yymsp[-3].minor.yy96 = yylhsminor.yy96;
        break;
      case 32: /* ruby_opts ::= ruby_opts COMMA STRING */
#line 402 "src/gemfile/parser.y"
{
    yylhsminor.yy96 = yymsp[-2].minor.yy96;
    memset(&yymsp[-2].minor.yy96, 0, sizeof(yymsp[-2].minor.yy96));
    /* ruby "~> 3.2", ">= 3.2.1" -- version constraints, ignored */
}
#line 1558 "src/gemfile/parser.c"
  yymsp[-2].minor.yy96 = yylhsminor.yy96;
        break;
      case 33: /* gemspec_stmt ::= GEMSPEC gemspec_opts */
#line 412 "src/gemfile/parser.y"
{
    gf->has_gemspec = true;
}
#line 1566 "src/gemfile/parser.c"
  yy_destructor(yypParser,68,&yymsp[0].minor);
        break;
      case 34: /* file ::= stmts */
{  yy_destructor(yypParser,53,&yymsp[0].minor);
#line 122 "src/gemfile/parser.y"
{
}
#line 1574 "src/gemfile/parser.c"
}
        break;
      case 35: /* stmts ::= stmts stmt */
{  yy_destructor(yypParser,53,&yymsp[-1].minor);
#line 124 "src/gemfile/parser.y"
{
}
#line 1582 "src/gemfile/parser.c"
  yy_destructor(yypParser,54,&yymsp[0].minor);
}
        break;
      case 37: /* stmt ::= source_stmt */
{  yy_destructor(yypParser,55,&yymsp[0].minor);
#line 127 "src/gemfile/parser.y"
{
}
#line 1591 "src/gemfile/parser.c"
}
        break;
      case 38: /* stmt ::= gem_stmt */
{  yy_destructor(yypParser,56,&yymsp[0].minor);
#line 128 "src/gemfile/parser.y"
{
}
#line 1599 "src/gemfile/parser.c"
}
        break;
      case 39: /* stmt ::= group_stmt */
{  yy_destructor(yypParser,57,&yymsp[0].minor);
#line 129 "src/gemfile/parser.y"
{
}
#line 1607 "src/gemfile/parser.c"
}
        break;
      case 40: /* stmt ::= ruby_stmt */
{  yy_destructor(yypParser,58,&yymsp[0].minor);
#line 130 "src/gemfile/parser.y"
{
}
#line 1615 "src/gemfile/parser.c"
}
        break;
      case 41: /* stmt ::= gemspec_stmt */
{  yy_destructor(yypParser,59,&yymsp[0].minor);
#line 131 "src/gemfile/parser.y"
{
}
#line 1623 "src/gemfile/parser.c"
}
        break;
      case 42: /* stmt ::= platforms_stmt */
{  yy_destructor(yypParser,60,&yymsp[0].minor);
#line 132 "src/gemfile/parser.y"
{
}
#line 1631 "src/gemfile/parser.c"
}
        break;
      case 43: /* stmt ::= plugin_stmt */
{  yy_destructor(yypParser,61,&yymsp[0].minor);
#line 133 "src/gemfile/parser.y"
{
}
#line 1639 "src/gemfile/parser.c"
}
        break;
      case 46: /* array ::= LBRACKET array_items RBRACKET */
#line 312 "src/gemfile/parser.y"
{
}
#line 1646 "src/gemfile/parser.c"
  yy_destructor(yypParser,63,&yymsp[-1].minor);
        break;
      case 51: /* array_items ::= array_items COMMA SYMBOL */
      case 52: /* array_items ::= array_items COMMA STRING */ yytestcase(yyruleno==52);
{  yy_destructor(yypParser,63,&yymsp[-2].minor);
#line 318 "src/gemfile/parser.y"
{
}
#line 1655 "src/gemfile/parser.c"
}
        break;
      case 53: /* platforms_open ::= PLATFORMS platform_names DO */
#line 363 "src/gemfile/parser.y"
{
}
#line 1662 "src/gemfile/parser.c"
  yy_destructor(yypParser,67,&yymsp[-1].minor);
        break;
      case 55: /* platform_names ::= platform_names COMMA SYMBOL */
{  yy_destructor(yypParser,67,&yymsp[-2].minor);
#line 370 "src/gemfile/parser.y"
{
}
#line 1670 "src/gemfile/parser.c"
}
        break;
      case 57: /* gemspec_opts ::= gemspec_opts COMMA KEY STRING */
      case 58: /* gemspec_opts ::= gemspec_opts COMMA KEY SYMBOL */ yytestcase(yyruleno==58);
{  yy_destructor(yypParser,68,&yymsp[-3].minor);
#line 419 "src/gemfile/parser.y"
{
}
#line 1679 "src/gemfile/parser.c"
}
        break;
      case 63: /* gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET STRING */
      case 64: /* gemspec_opts ::= gemspec_opts COMMA SYMBOL HASHROCKET SYMBOL */ yytestcase(yyruleno==64);
{  yy_destructor(yypParser,68,&yymsp[-4].minor);
#line 429 "src/gemfile/parser.y"
{
}
#line 1688 "src/gemfile/parser.c"
}
        break;
      default:
      /* (36) stmts ::= */ yytestcase(yyruleno==36);
      /* (44) stmt ::= GIT_SOURCE */ yytestcase(yyruleno==44);
      /* (45) stmt ::= NEWLINE */ yytestcase(yyruleno==45);
      /* (47) array ::= LBRACKET RBRACKET */ yytestcase(yyruleno==47);
      /* (48) array ::= PERCENT_ARRAY */ yytestcase(yyruleno==48);
      /* (49) array_items ::= SYMBOL */ yytestcase(yyruleno==49);
      /* (50) array_items ::= STRING */ yytestcase(yyruleno==50);
      /* (54) platform_names ::= SYMBOL */ yytestcase(yyruleno==54);
      /* (56) gemspec_opts ::= */ yytestcase(yyruleno==56);
      /* (59) gemspec_opts ::= KEY STRING */ yytestcase(yyruleno==59);
      /* (60) gemspec_opts ::= KEY SYMBOL */ yytestcase(yyruleno==60);
      /* (61) gemspec_opts ::= SYMBOL HASHROCKET STRING */ yytestcase(yyruleno==61);
      /* (62) gemspec_opts ::= SYMBOL HASHROCKET SYMBOL */ yytestcase(yyruleno==62);
      /* (65) plugin_stmt ::= PLUGIN STRING */ yytestcase(yyruleno==65);
      /* (66) plugin_stmt ::= PLUGIN STRING COMMA STRING */ yytestcase(yyruleno==66);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 114 "src/gemfile/parser.y"

    fprintf(stderr, "wow: Gemfile parsing failed\n");
#line 1751 "src/gemfile/parser.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 106 "src/gemfile/parser.y"

    (void)yymajor;
    (void)yyminor;
    fprintf(stderr, "wow: Gemfile syntax error at line %d\n",
            TOKEN.line);
    gf->_deps_cap = (size_t)-1;  /* signal error */
#line 1777 "src/gemfile/parser.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
