#define SOURCE                           1
#define GEM                              2
#define GROUP                            3
#define DO                               4
#define END                              5
#define RUBY                             6
#define GEMSPEC                          7
#define LIT_TRUE                         8
#define LIT_FALSE                        9
#define LIT_NIL                         10
#define STRING                          11
#define SYMBOL                          12
#define KEY                             13
#define COMMA                           14
#define HASHROCKET                      15
#define NEWLINE                         16
#define IDENT                           17
#define UNSUPPORTED                     18
#define ERROR                           19
#define GIT_SOURCE                      20
#define PLUGIN                          21
#define PLATFORMS                       22
#define PATH                            23
#define GIT                             24
#define GITHUB                          25
#define INSTALL_IF                      26
#define LBRACKET                        27
#define RBRACKET                        28
#define LPAREN                          29
#define RPAREN                          30
#define PERCENT_ARRAY                   31
#define IF                              32
#define UNLESS                          33
#define ELSE                            34
#define ELSIF                           35
#define EVAL_GEMFILE                    36
#define EQ                              37
#define NEQ                             38
#define GTE                             39
#define LTE                             40
#define GT                              41
#define LT                              42
#define MATCH                           43
#define AND                             44
#define OR                              45
#define BANG                            46
#define ASSIGN                          47
#define DOT                             48
#define COLON_COLON                     49
#define PIPE                            50
#define QUESTION                        51
#define INTEGER                         52
#define FLOAT_LIT                       53
